### ISSUE TITLE
Crop not work?

### ISSUE THREAD

**Issue by delphiprogramming** [viliusle/miniPaint#100]
thanks

**Comment by viliusle** [comment]
Click crop green button on top, after you select something.

**Comment by avalero85** [comment]
I think there is an issue when you use the "crop" tool in Chrome. Many times it does not crop well and the error "Empty selection" appears.

It only happens in Chrome, in the rest of browsers it has never happened to me.

**Comment by viliusle** [comment]
I saw it few times, but i can not reproduce it, if you can, please share exact steps, would be very helpful.

**Comment by avalero85** [comment]
It is very difficult to reproduce, I didn't  find a case that always fails. It is very random :(
