### ISSUE TITLE
edit save is not working for external urls

### ISSUE THREAD

**Issue by riz537** [viliusle/miniPaint#103]
Hi Viliusle,
 
  My requirement is to pass an image url (either from local file system like c:/riz.jpg or an online image url like http://demo/riz.jpg )  and then it should appear on the mini paint then the user can edit it and save as the way he want.

the code present in examples folder - open -edit and save it working only if the image is present in the image folder of the project . I tried giving an external  online url but its appearing on mini paint but after doing the editing its not saving . Its throwing errors .

Here is the code . I just changed the image src property  to external URL
 src="http://ZZZZZ/xyz.jpg" onclick="open_image(this)" 

One more doubt i have is do I need to entire code given in the GIT repository of only iframe integration is enough .

<iframe id="myFrame" style="width:100%;height:70vh;border:0;" src="../"></iframe> --> Can you explain what is src=../  . I did not understand where this src is pointing to ?

Please help here . 

Thanks 
Rizwan

**Comment by viliusle** [comment]
For iframe, you only need dist/*, images/* and index.html.

If you try to open image from web - there is chance to get CORS error, i replied about it here:
https://github.com/viliusle/miniPaint/issues/104

>Can you explain what is src=../
src must point to folder, where is minipaint code. In my example code it was 1 folder up, in your project it depends where you will put it. It can be for example src="libs/minipaint/"
