### ISSUE TITLE
Cross origin error with mini paint on open_image function

### ISSUE THREAD

**Issue by riz537** [viliusle/miniPaint#104]
Hi viliusle,

     I got a requirement to edit a selected image either from local file system or from an online image url  and the save it . I saw the git code and written as follows but its throwing cross origin error as below.

**Uncaught DOMException: Blocked a frame with origin xxx from accessing a cross-origin frame.
    at open_image (index.html :21:63)**

Is there any way to pass a image URL either from local system like c:/abc/riz.jpg and also from an online url like http://abc/xyx/riz.jpg.

kindly suggest what needs to be done 

Here is the complete code that i am using.

<!DOCTYPE HTML>
<html>

	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

		<title>Image Editor</title>

	</head>
	<body>
     <iframe id="myFrame" style="width:100%; height:500px;"  src="https://viliusle.github.io/miniPaint/"></iframe>
     <img  id="my_image" src="http://xxxx/yyyy/riz.jpg"  onclick="open_image('my_image');"  />
     
	<script type="text/javascript">

function open_image(image){
	if(typeof image == 'string'){
		image = document.getElementById("my_image");
	}
	var Layers = document.getElementById('myFrame').contentWindow.Layers;
	var name = image.src.replace(/^.*[\\\/]/, '');
	var new_layer = {
		name: name,
		type: 'image',
		data: image,
		width: image.naturalWidth || image.width,
		height: image.naturalHeight || image.height,
		width_original: image.naturalWidth || image.width,
		height_original: image.naturalHeight || image.height,
	};
	Layers.insert(new_layer);
}

		</script>
	
	</body>

</html>

Please help with exact code to achieve this functionality .

**Comment by viliusle** [comment]
You can not open local files without user actions.
If you want to open image from web, that server, that stores image, must also provide CORS header. If not - you will get error.  You have to use server side scripts here, for example PHP, that will work in 100% cases. So that scripts acts like proxy between your JS and remote image.
