### ISSUE TITLE
Erasing on multiple layers

### ISSUE THREAD

**Issue by STPJ** [viliusle/miniPaint#105]
Hi, I've done several modifications on miniPaint. 

One feature I am trying to implement is the Erasing on all layers at once.
I basicly throw in a loop convertion to all layers as Raster (Does give a 2 sec delay).

I bind it on the Erase icon to make it look more 'fluid'.
I have having implementing the several layer loop in erase.js.
By what I understand you are creating a Temporary Canvas of the current layer and then substract the drawing done on this canvas to other layers?

I've try to add a 
`config.layers.forEach(layer){ 
     config.layer = layer;
      And the remaining of the method of erase_general`

Not much luck.

Can you point me on a few hints so I can code that properly?
Love your coding structure btw.

**Comment by STPJ** [comment]
Never mind. I've found how and made it work.

Thanks.

**Comment by RageGamerBoi** [comment]
Could this be made into a separate tool and put in the main project?
This feature is more necessary than other programs as each brush stroke becomes a separate layer.
