### ISSUE TITLE
How can I set the crop window by aspect ratio?

### ISSUE THREAD

**Issue by sraddhaKar** [viliusle/miniPaint#109]
I want to fix the aspect-ratio of crop-window. How can I do that?

**Comment by viliusle** [comment]
All you need to edit is this file. And i bellieve it should be clear what to do. 
I recommend on mousemove and mouseup functinos check if ctrl key is pressed, then change width and height to have same ratio as global width and height.

https://github.com/viliusle/miniPaint/blob/master/src/js/tools/crop.js

If you do this, please send me code back, i would like to integrate this too.

**Comment by sraddhaKar** [comment]
Thank you for the reference. 
I have done the functionality. If you want to integrate it, here is the code:

1.  Add below line of code in `config.js` file after line no `172`

`type: {
value: 'Free',
values: ['Free', '16:9', '4:3', '2:3', '1:1'],
},`

2. Add below line of code in `crop.js` file in place of line no `109`

`if (config.TOOL.attributes.type.value == 'Free') {
            var height = mouse.y - mouse.click_y;
        } else if (config.TOOL.attributes.type.value == '16:9') {
            var height = width * (9 / 16);
        } else if (config.TOOL.attributes.type.value == '4:3') {
            var height = width * (3 / 4);
        } else if (config.TOOL.attributes.type.value == '2:3') {
            var height = width * (3 / 2);
        } else if (config.TOOL.attributes.type.value == '1:1') {
            var height = width;
        }`
