### ISSUE TITLE
Free hand skew 

### ISSUE THREAD

**Issue by nikhilkhot46** [viliusle/miniPaint#111]
Hello Team,

I want to skew image with free dimension is there any possibility to do it.

This is the link for demo https://pixlr.com/editor/ upload image->click on edit menu->click on free distort->change image from moving points.

**Comment by nikhilkhot46** [comment]
i am not getting JS lib for free distort. :(

**Comment by viliusle** [comment]
Writing it yourself would be really hard. Try also searching for: "Free Transform", should be same.

**Comment by viliusle** [comment]
Status update, added to TODO, but JS library for Free Transform must be found in order to implement it. When i will have time, i will search for solution.

**Comment by viliusle** [comment]
wont be implemented, unless something will change.
