### ISSUE TITLE
Layers Grouping

### ISSUE THREAD

**Issue by darkworks** [viliusle/miniPaint#112]
Hi minipaint team 

i was thinking of layers grouping feature , like we group layers in photoshop under folder.
so what will be the proper steps to add it to minipaint , i guess dragging of layers it will need too

thanks

**Comment by viliusle** [comment]
Layer object already has parent_id, its just not used, was reserved for future. Now you will use it. Basically i see these steps:

- use that parent_id to create listing like tree, not simple list that we have now.
- add ability in GUI (layers block in right sidebar) to create folder, group several layers, ungroup, create new layer in selected folder. Probably finding good lib with drag&drop would be best here. and all possible action should be available, for example move some layer to directory, or out of directory, delete directory with contents, hide directory with content inside.
- Check every module, tool that use layers. Add grouping support there too, if its needed.

So layers list will become something like:

layer1
layer2
directory
----- layer3
------directory
------|----layer5
layer6

Directory can be layer object with type=directory. Layer3 will ahve parent_id same as directory id.

**Comment by darkworks** [comment]
ok good  , i will try this , will let u know how it goes 

thanks
