### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by terryjohnbradford** [viliusle/miniPaint#113]
I can't for the life of me get this to install. 

Can someone document the requirements and process for install - I know there is a short guide which suggests it should basically just install itself but I'm failing to get this working. 

It fails for me at : npm run server with a range of errors that I have tried to resolve to no avail.

**Comment by terryjohnbradford** [comment]
just went to try a fresh build and capture all errors but the build page is error 400 - maybe it's being updated ?

**Comment by viliusle** [comment]
Something wrong with server, for now, use:
https://webcache.googleusercontent.com/search?q=cache:sbG8G3AD9vYJ:https://github.com/viliusle/miniPaint/wiki/Build-instructions+&cd=2&hl=en&ct=clnk&gl=lt

**Comment by viliusle** [comment]
If issue is not fixed, reopen and give more info.
