### ISSUE TITLE
Zoomed In Copy & Paste Fail

### ISSUE THREAD

**Issue by rklockner** [viliusle/miniPaint#115]
If I zoom in on an image, then attempt to copy/paste a portion of the image, the image becomes locked (I can't make any changes).  If I attempt to zoom (in or out), the image area turns white.

At this point, the only thing I can do is refresh the page.

**Comment by viliusle** [comment]
Can not reproduce, what is your browser? Also if you can reproduce it, please send me console log, it should have errors probably.

**Comment by rklockner** [comment]
It seems to be working today...  If I can reproduce it more regularly, I will let you know.  Thanks for the quick reply!
