### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by bluenevus** [viliusle/miniPaint#117]
do you have a docker image for this?  I tried and tried to get this built in docker but it errors out so I was hoping you might have one.

**Comment by viliusle** [comment]
i dont have. Can you give error log? maybe somebody will help.

**Comment by bluenevus** [comment]
will do.  can you tell me what distro and what version of that distro you have it running on so I can use that as the base image

**Comment by viliusle** [comment]
I don't have docker, but building was tested on windows, linux, also inside Vagrant with Ubuntu. 

Also make sure you have NPM at least 6. This is important!

**Comment by viliusle** [comment]
Can you run ` npm --version ` ?

Also some this link can help:
https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver

**Comment by bluenevus** [comment]
sorry it took so long.  NPM 6.3

Step 13/13 : RUN npm run build


 ---> Running in 2417b406527b

[91mnpm[0m
[91m [0m
[91mERR![0m
[91m missing script: build
[0m
[91m
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m A complete log of this run can be found in:
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m     /root/.npm/_logs/2018-08-09T20_28_22_343Z-debug.log
[0m
Removing intermediate container 2417b406527b

The command '/bin/sh -c npm run build' returned a non-zero code: 1

**Comment by bluenevus** [comment]
also, if I tell it to run instead of build...still can't seem to find the script

Step 13/13 : RUN npm run server


 ---> Running in 9de11c4d896a

[91mnpm[0m
[91m [0m
[91mERR![0m
[91m missing script: server
[0m
[91m
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m A complete log of this run can be found in:
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m     /root/.npm/_logs/2018-08-09T20_35_04_651Z-debug.log
[0m
Removing intermediate container 9de11c4d896a

The command '/bin/sh -c npm run server' returned a non-zero code: 1

**Comment by viliusle** [comment]
I read about it, and i believe that all these issues are related with npm issues with specific environment. **Again, make sure you have latest NPM**. Install is not enough, did test few days ago, installing NPM on vagrant gave me 5 years age version...

**Comment by bluenevus** [comment]
I'm definitely on npm 6.3.0 and nodejs 10x

I didn't use the repo out of the box or epel.

did one of these curl -sL https://rpm.nodesource.com/setup_10.x<https://rpm.nodesource.com/setup_8.x> | sudo bash -

to get the latest version of node and npm 6.3 and its set as global

Get Outlook for Android<https://aka.ms/ghei36>



________________________________

**Comment by ucay** [comment]
AFAIK, you need to use single line commands.

> RUN cd ~/miniPaint && npm run build

or use WORKDIR

**Comment by bluenevus** [comment]
thanks I finally got it to build

https://github.com/bluenevus/docker-minipaint/blob/master/Dockerfile

https://hub.docker.com/r/bluenevus/docker-minipaint/

still have to test it with a pull

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bluenevus** [comment]
one quick question.  I have it built.  Does it run after the build or do I need to do something like npm start because I can't connect to it on localhost:8080... but I see it running

:22 node /var/miniPaint/node_modules/.bin/webpack-dev-server --mode development --open

> miniPaint@4.1.1 server /var/miniPaint


> webpack-dev-server --mode development --open




ℹ ｢wds｣: Project is running at http://localhost:8080/


ℹ ｢wds｣: webpack output is served from /dist/


ℹ ｢wds｣: Content not from webpack is served from ./


⚠ ｢wds｣: Unable to open browser. If you are running in a headless environment, please do not use the open flag.


ℹ ｢wdm｣: Hash: 357d6d8295129a82bf1d


Version: webpack 4.12.0


Time: 12730ms


Built at: 08/10/2018 1:57:22 AM


        Asset      Size  Chunks             Chunk Names


    bundle.js  2.21 MiB    main  [emitted]  main


bundle.js.map  1.88 MiB    main  [emitted]  main


Entrypoint main = bundle.js bundle.js.map


[./node_modules/babel-polyfill/lib/index.js] 833 bytes {main} [built]


[./node_modules/core-js/fn/regexp/escape.js] 108 bytes {main} [built]


[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.75 KiB {main} [built]


[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]


[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {main} [built]


[./src/css/menu.css] 1.08 KiB {main} [built]


[./src/css/print.css] 1.09 KiB {main} [built]


[./src/css/reset.css] 1.09 KiB {main} [built]


[./src/js/config.js] 3.24 KiB {main} [built]


[./src/js/core/base-gui.js] 14.8 KiB {main} [built]


[0] multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/js/main.js 52 bytes {main} [built]


[./src/js/core/base-layers.js] 27.8 KiB {main} [built]


[./src/js/core/base-state.js] 7.64 KiB {main} [built]


[./src/js/core/base-tools.js] 9.66 KiB {main} [built]


[./src/js/main.js] 1.4 KiB {main} [built]


    + 503 hidden modules


ℹ ｢wdm｣: Compiled successfully.

**Comment by bluenevus** [comment]
and when I take a closer look 
webcache        8080/tcp        http-alt        # WWW caching service
webcache        8080/udp        http-alt        # WWW caching service

**Comment by ucay** [comment]
You just need to access the index.html directly. Because build is for production.
It serve to complete build process. After that it closed again.
If you have web server, try point your host (or virtualhost) to miniPaint's directory.

#cmiiw

**Comment by analogue** [comment]
App is listening on localhost (127.0.0.1) in the container instead of the interface attached to the docker bridge.  You can fix by passing `--host 0.0.0.0` to the cmd line used to launch the server in package.json.
