### ISSUE TITLE
Crop aspect ratio

### ISSUE THREAD

**Issue by bunnyhu** [viliusle/miniPaint#120]
There is any possibility to set an aspect radio for cropping? It would be a nice feature!

**Comment by bunnyhu** [comment]
It's good to know, thanks! But sometimes I need fix and different ratio from original one, that's why I like to see this feature. For example I like to take an exact 4:3 or 1:1 ratio from a picture.

**Comment by viliusle** [comment]
Menu > Image > "Size" can also help.

**Comment by bunnyhu** [comment]
Close but not perfect.  Because the CTRL key, you already using aspect ration, so it need only enable to set manual and lock it. Perhaps sometime in the next versions you can make it. Just a suggestion :)

**Comment by sraddhaKar** [comment]
Hello @bunnyhu ,

I understand what you are hoping. I did for 1:1, 4:3, 2:3 and 16:9. if you want you can add the following code in your project.

[https://github.com/viliusle/miniPaint/issues/109#issuecomment-403812167](url)

Hoping this is what you are looking for.

Regards,
Sraddha

**Comment by bunnyhu** [comment]
Hey,

Thanks for the idea! Its a bit hardcoded, perhaps two input box is better
then you can set any ratio but this is a fast solution for my problem!
Personally I need only a few ratio, so your solution for me is perfect.
Thanks again, mate!
Karoly

Editor in chief: www.divecenter.hu , www.divingiscool.com
www.bunny.hu | skype:bunny.hu | bunny.divecenter@gmail.com


Sraddha Kar <notifications@github.com> ezt írta (időpont: 2018. aug. 25.,
Szo, 8:06):

**Comment by sraddhaKar** [comment]
Its my pleasure Karoly.
