### ISSUE TITLE
How to start miniPaint in french ?

### ISSUE THREAD

**Issue by axel584** [viliusle/miniPaint#122]
Hi,
I'm sorry to ask this on the issues (may be the issues could be "improve the documentation" ?) But I would like to start miniPaint directly in french, and I didn't find in the documentation how to do that.

Thank you for your help,

Axel

**Comment by viliusle** [comment]
Issues are for any type of things, don't be afraid to create it.

You can not start miniPaint directly in french now. But you can fork project and change default language to "fr" for now:
https://github.com/viliusle/miniPaint/blob/master/src/js/core/base-gui.js#L224

Or even better, modify that function to allow ?lang=xx parameter. (get them using `this.Helper.get_url_parameters();` )

i think i will implement it some time later.

**Comment by viliusle** [comment]
added to master, will be moved to live on next update.
