### ISSUE TITLE
Zoom Issue

### ISSUE THREAD

**Issue by theevilqueen77** [viliusle/miniPaint#125]
Zooming in on tiny images stretches the art board and image causing huge loss of quality. Is there an easy way to implement it so that it basically zooms into that specific area without causing pixelization?

**Comment by viliusle** [comment]
I dont see that using random small image. Please provide more information, including sample image, browser, OS, screenshot.

**Comment by theevilqueen77** [comment]
Here's an example. This is an extremely tiny image, but something my clients could potentially be using quite frequently.

![example](https://user-images.githubusercontent.com/27788529/45314795-be2c4580-b500-11e8-8d36-70fbf416fdb7.PNG)

**Comment by viliusle** [comment]
I don't see anything wrong here. What do you expect correct behavior here?

**Comment by theevilqueen77** [comment]
I realized that when I tried replicating this with an image editor application that I was using it was more like Illustrator and not Photoshop. Sorry about that!
