### ISSUE TITLE
electron app

### ISSUE THREAD

**Issue by bluenevus** [viliusle/miniPaint#126]
just letting you know that I appreciate your help with the docker issue.  we just couldn't get it resolved so we created an electron app for the desktop.  Your app works perfectly as a desktop app using electron.  Highly recommended for anyone looking at using this.

**Comment by viliusle** [comment]
So it worked in the end, good to know. Closing, since this is not issue.

p.s. if you have more related information, that can be useful to others, feel free to reopen and share.

**Comment by bluenevus** [comment]
If you don’t mind, we will post it on the electron apps hub.  Credit will be yours.  We just need a place to hang it

--- vr, Frank

**Comment by viliusle** [comment]
ok
