### ISSUE TITLE
Magic Wand Tool Enhancement

### ISSUE THREAD

**Issue by banrionjackie** [viliusle/miniPaint#127]
Would it be possible to get the magic wand tool to select the areas instead of automatically deleting it? And being able to select multiple areas by using shift+click?

**Comment by chexbox** [comment]
It'll take some work, as currently selections are only rectangles.

**Comment by theevilqueen77** [comment]
@chexbox ahhh, I wasn't sure how difficult it would be to transition from deleting it to simply selecting that area.

**Comment by viliusle** [comment]
Correct, there are few problems:

- currently selections are only rectangles
- if we add advanced selection, we also must change other tools for advanced selection, for example: move, copy+paste, fill, maybe erase, blur, sharpen, desaturate. Is there more actions for selection?

i agree that this should be implemented in general (and using some magic wand JS libs, there are at least few ), but it would take more time than expected. So for now, priority is low at least for me. In future, we will see.

**Comment by chexbox** [comment]
We should prioritize making non-rectangle selections.

**Comment by viliusle** [comment]
closed, reason: priority is low, it would take lots of development.
