### ISSUE TITLE
bug : after rotation resize not work

### ISSUE THREAD

**Issue by darkworks** [viliusle/miniPaint#128]
i wonder if its bug when we rotate image then resize tool not work on it , before rotation resize work but once image is rotate you can no longer resize it

**Comment by viliusle** [comment]
It works, if image is in 0,0 coordinates, but if not, image stays in same coordinates, but outside of visible area. Bug confirmed.

**Comment by viliusle** [comment]
situation should be better after last resize updates (still on master only)
