### ISSUE TITLE
Modification required for magic wand tool

### ISSUE THREAD

**Issue by parth7695** [viliusle/miniPaint#13]
In the magic wand feature, the effect is applied on 2 click total, i.e one time you have to click on the magic wand tool icon and the next time you have to click on the canvas to get the effect applied, but what I want is, effect should be applied directly on clicking the magic wand icon by clicking just once and the effect should be applied from (x,y) corresponding to (0,0) on the canvas

**Comment by viliusle** [comment]
Both click are required for normal work for users. First - to activate function, show settings (you can change power and add alias) and second click - ask offset (x, y) and execute function. 

If you want some this with 1 click, you probably do some kind of macro. You can access function and use it as you like:
line 140, function tool_magic_wand
https://github.com/viliusle/miniPaint/blob/master/js/draw.js
