### ISSUE TITLE
Pixelization Of SVG Image When Adding Filters/Erase/Color Fill

### ISSUE THREAD

**Issue by WarrenIndLLC** [viliusle/miniPaint#130]
First. I think you did a great job on miniPaint. I’ve noticed that the NON CSS filters and other actions such as erase or fill (and many others), distort the SVG image that is on the Canvas. Is there any way to make it so if these filters or actions are performed ON an SVG image that it doesn’t distort the image?

**Comment by viliusle** [comment]
SVG is collection of vectors, So fill or erase can not edit or even touch SVG at all basically. 

Fill can be replaced with rectangle above svg as separate layer. 
Erase can be replaced to another layer  with white brush if transparency is off.

So all i can do is to show warning if user tries these actions on SVG file.

**Comment by WarrenIndLLC** [comment]
I see. Well, if the Fill, Erase, other Filters and other items don't work with SVGs, perhaps you can "disable" those selections for SVGs and when clicked on, the user gets a notification with some language instead of making that tool active. Then of course the user will have to close the popup and use the tools that are active that can be used with SVG images. Great work though!
