### ISSUE TITLE
Maintain image ratio when resizing layer

### ISSUE THREAD

**Issue by philooo2** [viliusle/miniPaint#132]
is it possible to maintain the aspect ratio when resizing a layer, using the mouse and dragging one of the layer corners ?

**Comment by philooo2** [comment]
I would like to see a function similar to the one you did for CROP, but for the layer themselves when using the simple select tool.

FYI, on mac os the shortcut for the aspect ratio in the crop tool is 'shift+command' ;) in case someone is looking for it.

**Comment by viliusle** [comment]
It can be solved very easily:

1. want to keep maintain ratio? use CTRL key.
2. want to keep aspect ration? Drag corner. Otherwise - drag sides.

**Please everybody share** which option (1 or 2) you prefer. After that i can add this feature quickly.

**Comment by viliusle** [comment]
Update: added 3rd way in comment above, just like latest Photoshop is working.
