### ISSUE TITLE
How to dynamically call json files ?

### ISSUE THREAD

**Issue by webcontributor** [viliusle/miniPaint#134]
Hey @viliusle ,

Thanks for awesome image editor, i am using

https://github.com/viliusle/miniPaint/blob/master/examples/open-edit-save.html

This is my url, https://mypancho.com/apps/elfinder/php/editors/ImageEditor/?img=https://mypancho.com/apps/elfinder/files/Women-In-Suit-Free-Commercial-Use-PNG-Image-720.png - This is working fine.

But we have save images in json format, and when trying to call json files it is not working, Please see given link

https://mypancho.com/apps/elfinder/php/editors/ImageEditor/?img=https://mypancho.com/apps/elfinder/files/Mypancho-logo-nocom-black-150x28.json

Please help me to fix this issue.

[index.zip](https://github.com/viliusle/miniPaint/files/2848072/index.zip)

Thanks in advanced.

**Comment by viliusle** [comment]
i will look at it.

**Comment by webcontributor** [comment]
Hey @viliusle ,

Any updates?

Thanks

**Comment by webcontributor** [comment]
Hey @viliusle , 

After update src/js/modules/file/open.js , 
It is working fine now. 

Thanks for your Help.
