### ISSUE TITLE
Comprehensive Apache2 conf file

### ISSUE THREAD

**Issue by iamdoubz** [viliusle/miniPaint#135]
First off, thank you for this program. It is truly _wonderful_ and as I move all my apps to being web based, miniPaint really adds a touch I couldn't even begin to comprehend how you wrote it.

This is not an issue, I just wanted to share my apache2 .conf file for those that like excessive security and such and for those that use the Apache2 web server.

## Requirements: ##
1. Apache version > 2.4
2. A bunch of mod's enabled (headers, proxy, proxy_balancer, proxy_http, proxy_wstunnel, rewrite, and there may be others but those are the ones I know off the top of my head)
3. I used git to clone into my /var/www/public_html/ and am _not_ using npm at all (having said that, it would be easy to use apache as a reverse proxy, but will not cover that in this post)
4. I am using Ubuntu 16.04, but this can be modified to account for other distros
5. I am using Let's Encrypt for my SSL certificates
## Results: ##
You will get an A+ on [Qualsys' SSL Server Test](https://www.ssllabs.com/ssltest/index.html) and an A+ on [netsparker Security Headers](https://securityheaders.com/).
## Config File: ##
      `<IfModule mod_ssl.c>
        define Public_Url miniPaint.domain.com
        define Install_Dir /var/www/public_html/miniPaint/
        define Admin_Email web@your.email
        ServerTokens Prod
        SSLStaplingCache "shmcb:${APACHE_LOG_DIR}/stapling-cache(150000)"
        SSLSessionCache "shmcb:${APACHE_LOG_DIR}/ssl_scache(512000)"
        SSLSessionCacheTimeout 300
    <VirtualHost *:443>
        ServerName ${Public_Url}
        ServerAdmin ${Admin_Email}
        DocumentRoot ${Install_Dir}
        ErrorLog ${APACHE_LOG_DIR}/${Public_Url}.error.log
        CustomLog ${APACHE_LOG_DIR}/${Public_Url}.access.log combined
    ###Security Hardening ###
        SSLProxyEngine On
        AddDefaultCharset utf-8
        HostnameLookups Off
        UseCanonicalName Off
        ProxyBadHeader Ignore
        KeepAlive Off
        ProxyPreserveHost On
        ProxyRequests Off
        ProxyTimeout 600
        ProxyReceiveBufferSize 4096
        ProxyVia On
        SSLEngine On
        SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
        ServerSignature Off
        SSLCompression Off
        SSLUseStapling On
        SSLStaplingResponderTimeout 5
        SSLStaplingReturnResponderErrors Off
        SSLSessionTickets Off
        RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
        Header always set Strict-Transport-Security "max-age=15552000; preload"
        Header always set X-Content-Type-Options nosniff
        Header always set X-Robots-Tag none
        Header always set X-XSS-Protection "1; mode=block"
        Header always set X-Frame-Options "SAMEORIGIN"
        Header always set Referrer-Policy strict-origin-when-cross-origin
        Header always set Content-Security-Policy "default-src 'none'; script-src 'self' https://${Public_Url}; style-src 'self' 'unsafe-inline' https://${Public_Url}; object-src ${Public_Url}; img-src data: blob: https://${Public_Url};"
        Header always set Feature-Policy "geolocation 'self'; midi 'self'; sync-xhr 'self'; microphone 'self'; camera 'self'; magnetometer 'self'; gyroscope 'self'; speaker 'self'; fullscreen 'self'; payment 'self';"
    ###Certbot ssl/tls stuff ###
        #Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/${Public_Url}/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/${Public_Url}/privkey.pem
    </VirtualHost>
    <VirtualHost *:80>
        ServerName ${Public_Url}
        ServerAdmin ${Admin_Email}
        DocumentRoot ${Install_Dir}
        ErrorLog ${APACHE_LOG_DIR}/${Public_Url}.error.log
        CustomLog ${APACHE_LOG_DIR}/${Public_Url}.access.log combined
        RewriteEngine On
        RewriteCond %{SERVER_NAME} =${Public_Url}
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
    </VirtualHost>
    </IfModule>`

Or, see attached file.
[miniPaint.txt](https://github.com/viliusle/miniPaint/files/2943513/miniPaint.txt)

**Comment by viliusle** [comment]
Closing (moving to archive).
