### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by AndreFabris** [viliusle/miniPaint#136]
I would love to have light as default theme for all my users. I cannot find anything in the code to make it so. Any ideas?

Thanks,

Andre

**Comment by viliusle** [comment]
https://github.com/viliusle/miniPaint/blob/master/src/js/core/base-gui.js#L398

So basically you can change config.themes variable on config.php,  first value will be used by default, so make it:

```
config.themes = [
	'light',
	'dark',
	'green',
];
```

p.s. i am happy that somebody liked other than default theme.

**Comment by AndreFabris** [comment]
@viliusle I guess you meant config.js. However changing the order does not make a difference, believe me I actually tried that.

**Comment by viliusle** [comment]
I does work, but you have to clear cookies or open app in incognito window. So it also would work for new users, that comes first time.

p.s. i did not tested yesterday, but i did it today - it works in incognito window.
