### ISSUE TITLE
select from edge

### ISSUE THREAD

**Issue by cup** [viliusle/miniPaint#138]
if i want to crop just the height - or just the width - this program doesnt seem to have an easy way to do that

it seems you have to very carefully select the very edge pixel then drag across

you should be able to drag from beyond the edge making it simpler

**Comment by viliusle** [comment]
If you want to decrease width or height, go to image > size, and set new width and height here.
If you want to cut top for example, then yes, you have to use crop tool. But you CAN drag from beyond the edge, and release, system will fix size so you will get selection on edge.

**Comment by cup** [comment]
> But you CAN drag from beyond the edge, and release, system will fix size so you will get selection on edge.

@viliusle no, you cant. I just tried it

**Comment by viliusle** [comment]
You can, load some image, select crop tool, drag from image center to left-top corner, but drag little bit more and release. You will get some selection, now drag bottom right corner to right side (and even more) and close to bottom (lets leave some pixels here). Clicking "Crop" button will crop bottom of image. Top, left and right sides will remain unchanged.

**Comment by cup** [comment]
No, the request is:

From beyond the edge to the center

not:

from the center to beyond the edge
