### ISSUE TITLE
Warning in Firefox

### ISSUE THREAD

**Issue by Toad06** [viliusle/miniPaint#14]
Thank you for this soft.

I have this warning in Firefox : "Mutation Events is deprecated. Use MutationObserver instead."
in file : js/controlls.js
line 593 : document.getElementById('paste_ff').addEventListener('DOMSubtreeModified', function(){

I don't know if that means Mutation Events will be removed in the future.

**Comment by viliusle** [comment]
It will be fixed in next big stable update. 
Thank you for notice.
