### ISSUE TITLE
Merge with SVGEdit

### ISSUE THREAD

**Issue by anonimo82** [viliusle/miniPaint#141]
Look below

**Comment by anonimo82** [comment]
P.S.: Maybe then integrated with Tiki (https://tiki.org/HomePage)

**Comment by anonimo82** [comment]
P.S.: I removed the original post because I felt like it was very trollish, while this new idea I had seems better

**Comment by viliusle** [comment]
i checked Tiki, but i am not super happy about it, still does not understood what is it and why we need it.
And you have to download / install something?  Unless i am missing something.

Minipaint is all about  zero download, zero install, just use it.

**Comment by anonimo82** [comment]
In truth, I'm interested in Tiki just because it provides so many apps to work with, it's like a web OS on its own.
AFAIK, it also provide SVGEdit, so I tought hey, why not MiniPaint too?

Note I have nearly no experience with Tiki, while I have just a bit more with MiniPaint.

Thanks anyhow, I'm glad you checked out this.
