### ISSUE TITLE
What is the proper way of resizing the image?

### ISSUE THREAD

**Issue by selahattinalan** [viliusle/miniPaint#142]
Image/Size menu crops the image when I resized to a small image like the Photoshop canvas resize. But I want to resize the image with all layers and canvas together, like Photoshop image resize. How can I do this?

Actually from this image,
![Image1](https://user-images.githubusercontent.com/7167661/57098324-8c335200-6d22-11e9-9cd8-e092f294890c.png)

I don't want to obtain this image when I resize to 300x300px by using Image/Size menu.
![Image2](https://user-images.githubusercontent.com/7167661/57098326-8c335200-6d22-11e9-8b6d-144567711d74.png)

I want to obtain this image (All image with smaller piksels).
![Image3](https://user-images.githubusercontent.com/7167661/57098327-8c335200-6d22-11e9-96e0-34c765da3b3f.png)

I couldn't find a menu item or short way.

Thanks!

**Comment by viliusle** [comment]
Use Image > resize (but check "layers: all")
