### ISSUE TITLE
Line stabiliser

### ISSUE THREAD

**Issue by IchigoDaifuku** [viliusle/miniPaint#143]
Maybe there could be a togglable line stabiliser for the pencil or a way to create curved lines using the line tool? It's hard to make curved lines on a computer because my hands shake a bit, messing up the lines

**Comment by viliusle** [comment]
i would like it too.

**Comment by IchigoDaifuku** [comment]
I found a resource that might be useful https://github.com/opentoonz/opentoonz/issues/81

**Comment by wwderw** [comment]
Maybe even something like a bezier pen tool would be helpful that could later be rasterized in order to apply effects to.  SVG-edit has the pen tool, something along those lines.

**Comment by viliusle** [comment]
Also related:
https://codepen.io/kangax/pen/zofsp - really nice JS example
