### ISSUE TITLE
Picking colours with HSL is buggy

### ISSUE THREAD

**Issue by IchigoDaifuku** [viliusle/miniPaint#144]
Sometimes when I pick a colour by typing into the HSL boxes, one of the colours will inexplicably change to some other number. I'm not quite sure if this is intentional, but it makes picking specific HSL values very difficult.

![Screen Shot 2019-05-03 at 4 08 54 pm](https://user-images.githubusercontent.com/25236479/57122017-5c398c80-6dbe-11e9-8d96-feb9c3b44b1f.png)
![Screen Shot 2019-05-03 at 4 09 07 pm](https://user-images.githubusercontent.com/25236479/57122019-6196d700-6dbe-11e9-96fe-645cfcbb584e.png)
![Screen Shot 2019-05-03 at 4 09 23 pm](https://user-images.githubusercontent.com/25236479/57122021-6491c780-6dbe-11e9-810f-6aa0a2de0d55.png)

**Comment by viliusle** [comment]
1 RGB color can have few HSL values, when you change HSL, i convert it only to RGB to store it in memory, so i loose specific HSL value and in some cases i can not convert it back to HSL you want. 

It should be fixed by storing RGB and HSL values in memory. Bug confirmed.

**Comment by IchigoDaifuku** [comment]
Thanks!

**Comment by viliusle** [comment]
sorry, will be closed after commit will reach live ENV
