### ISSUE TITLE
Change And Redeploy 

### ISSUE THREAD

**Issue by llevens-traffic-its** [viliusle/miniPaint#145]
How can i change code and redeploy it for my own Project? and include it via Iframe?

**Comment by viliusle** [comment]
if you want to edit code, read build wiki: https://github.com/viliusle/miniPaint/wiki/Build-instructions

if you want to use it in some page, check examples: https://github.com/viliusle/miniPaint/wiki/Examples

**Comment by llevens-traffic-its** [comment]
And how to use the changes Files in Angular/typescript?

**Comment by llevens-traffic-its** [comment]
?

**Comment by viliusle** [comment]
i can not help you with Angular/typescript, maybe anybody else will.
