### ISSUE TITLE
Wipe problem, redo

### ISSUE THREAD

**Issue by Destiny1221** [viliusle/miniPaint#147]
How to Solve the Flash Problem of Wipe Pictures

**Comment by Destiny1221** [comment]
thanks!

**Comment by Destiny1221** [comment]
hi，I need a feature that restores the last step of undoing content. I want to store each discarded content in an array and then put it in a layer array, but I can't find every discarded layer content.

**Comment by Destiny1221** [comment]
I need to redo the previous function. Can you give me some ideas?

**Comment by viliusle** [comment]
You can find undo logic on `src/js/core/base-state.js`. Data is saved on variable `this.layers_archive`. You need:

1. in begining of undo() function, you need to create and call function save_for_redo() which saves current data into lets say this.layers_archive_redo. (new function is similar to save())
2. in begning of save(), clear this.layers_archive_red variable.
3. create function redo(), which restore state from this.layers_archive_redo. (function is similar to undo())
