### ISSUE TITLE
The erase tool can erase a image background (lock layer)

### ISSUE THREAD

**Issue by Usern2me** [viliusle/miniPaint#149]
Hi😀,i done some modifications according to my feature, my feature is edit one image at time,but can't drag this image through mouse.now i meet two problems.
1. I want to set image as background and can't drag this image,because the handwriting can't follow the picture to move,so now i don't know how to do.
2. erase tool can erase image content,but i don't want to erase this image,just erase handwriting and others is ok.
Can you point me on a few hints?thank you❤.

**Comment by viliusle** [comment]
Hello,
So you need additional feature/attribute for each layer: ability to lock it.

- add additional attribute to layer: is_locked = true
- add ability to toggle lock on/off for user using GUI (from menu?), like visibility.
- on layers list, if layer is locked, you must clearly see it, so add additional icon on locked layer.
- for each tool that you want to follow this new rule (select tool and erase?), add modifications, basically check if layer is locked, don't do anything, but show warning, that layer is locked and action can not done.

Its not that much to do. And its nice feature that exists in Photoshop. 
If you do this, share it. I would like to have it on main repository.

**Comment by Usern2me** [comment]
> Hello,
> So you need additional feature/attribute for each layer: ability to lock it.
> 
> * add additional attribute to layer: is_locked = true
> * add ability to toggle lock on/off for user using GUI (from menu?), like visibility.
> * on layers list, if layer is locked, you must clearly see it, so add additional icon on locked layer.
> * for each tool that you want to follow this new rule (select tool and erase?), add modifications, basically check if layer is locked, don't do anything, but show warning, that layer is locked and action can not done.
> 
> Its not that much to do. And its nice feature that exists in Photoshop.
> If you do this, share it. I would like to have it on main repository.

oooook,i'll try. thank you.

**Comment by Usern2me** [comment]
> Hello,
> So you need additional feature/attribute for each layer: ability to lock it.
> 
> * add additional attribute to layer: is_locked = true
> * add ability to toggle lock on/off for user using GUI (from menu?), like visibility.
> * on layers list, if layer is locked, you must clearly see it, so add additional icon on locked layer.
> * for each tool that you want to follow this new rule (select tool and erase?), add modifications, basically check if layer is locked, don't do anything, but show warning, that layer is locked and action can not done.
> 
> Its not that much to do. And its nice feature that exists in Photoshop.
> If you do this, share it. I would like to have it on main repository.

hello,can i ask another question.How to combine two or more layers into one layer,and change all other layers to one.becouse I want to erase all handwriting under the background picture with an eraser.Its traversing calls method `convert_layer_to_canvas` in `tmpCanvasCtx` ?
