### ISSUE TITLE
I want to keep the default theme as theme-light (rather theme-dark)

### ISSUE THREAD

**Issue by SirajChaudhary** [viliusle/miniPaint#168]
I want to keep the default theme as theme-light (rather theme-dark). Which file i need to visit to change this property (I don't find it in any CSS file body.theme-light)

**Comment by viliusle** [comment]
Change `config.themes` , first item is usedby default:
https://github.com/viliusle/miniPaint/blob/master/src/js/config.js#L23

After chaning it, you will need to rebuild dist/bundle.js and clean old cookies (or use incognito).
