### ISSUE TITLE
Smooth dragging?

### ISSUE THREAD

**Issue by pillows** [viliusle/miniPaint#17]
Would it be possible to have smooth dragging of the picture so there isn't a shadow when dragging it throughout the canvas?

**Comment by viliusle** [comment]
please explain exactly what you do to get this shadow, i need more information to reproduce it.

**Comment by pillows** [comment]
If you open up a picture on miniPaint and then drag it around you will see that there is a copy of the image on it's original spot while you have the image still dragging on your cursor.

**Comment by viliusle** [comment]
Fixed on dev. It looks much more better. It should reach live this week i hope.
