### ISSUE TITLE
[Feature Request] Non-destructive effects, similar to photoshop adjustment layers

### ISSUE THREAD

**Issue by Giwayume** [viliusle/miniPaint#170]
I don't see a lot of photo manipulation programs do this, but it would be awesome if each layer could have its own effect stack that recalculates the effect automatically whenever the layer is changed, as opposed to applying the effect once and relying on the undo history to get rid of it. 

This is similar to how a DAW typically works when manipulating audio, or how Blender handles modifiers. In Blender, modifiers (the equivalent of effects in this case) are never applied permanently unless you explicitly choose to do so after adding them. They're first added to a modifier stack so you can keep editing with the modifiers in place.

I'm not expecting real-time application of effects here, as I know many are intensive to calculate. But it would be nice to 1-up many other raster image editors with a non-destructive workflow.

Also going along with this, vector layers should automatically be rasterized for display when applying effects, but keep the source vector data. So you're still modifying it as a vector, but the effect makes a rasterized copy in memory for display on screen. The way this currently prompts you to rasterize a bit of a usability issue, I don't see any reason this should be a limitation beyond what everyone else does, "copy the Photoshop model". Photoshop is old and could be improved dramatically.

**Comment by viliusle** [comment]
Some filters are non-destructive, look at effects > CSS (name should be improved - @todo), but others are really slow, it could work with small images, but working on large images would make everything very slow.

But still, some can be moved to non-destructive. So basically this needs testing on my side.

**Comment by Giwayume** [comment]
The CSS filters is kind of what I'm talking about, except it should bake the effect instead of calculating it every frame so it doesn't slow down working in the tool.

**Comment by viliusle** [comment]
Actually app is not repainting everything on every frame, but only when there is actually change, like move, zoom, edit actions and so on. But still, as i said, i need to test everything.

Idea about web workers is good, interesting, but it would take time to implement it and web workers itself gives some speed loss. 

@todo - test web workers.

**Comment by Giwayume** [comment]
> move, zoom, edit

Basically the same effect, yeah. I mean you can bake the result of a CSS filter into an image and display that image instead of recalculating the CSS filter every time you do one of those actions.

**Comment by viliusle** [comment]
i just tested, and its only 2/22 effects can be converted into non-destructive, for simple reason: rendering 1 frame on 4600x2100 image would take 2-5 seconds. So for today it is too slow.

**Comment by Giwayume** [comment]
That's can be resolved through web workers, progress bars, and clever UI. I'll look at it in the future when I get the time.
