### ISSUE TITLE
[Usability] Allow tools to work in the empty area around the canvas

### ISSUE THREAD

**Issue by Giwayume** [viliusle/miniPaint#176]
With many tools it's awkward to use them around the edges of the canvas. For example:

* When drawing with the pencil, try to draw a line to one of the edges of the canvas. Depending on how fast your mouse moves, the sampling may be low enough that the line never reaches the edge because your pointer moved off canvas.
* When using selection or crop tool, it would be nice to be able to select starting from the empty area around the canvas in order to guarantee that the edges are selected.

I believe a quick fix for most tools would be instead of ignoring mouse movement that's outside of the canvas boundaries, instead report the mouse position as being at the very edge of the canvas when the mouse is outside.

Example of the pencil trying to draw to the edge:

![image](https://user-images.githubusercontent.com/4075314/95934242-6840c080-0d9e-11eb-8eab-138f8390eb6e.png)

**Comment by viliusle** [comment]
It was implemented to fix multiple issues having events outside of visible area. It can be improved, but it also would require lots of testing on every tool. 

I dont like that quick fix, we should try to allow outside events and see what happens.

Another idea is to allow events from inside, but not from outside (drawing circle from outside to inside should not work, but it should work from drawing from inside and dragging mouse to outside of visible area). This could work nicely.

**Comment by Giwayume** [comment]
>Another idea is to allow events from inside, but not from outside (drawing circle from outside to inside should not work, but it should work from drawing from inside and dragging mouse to outside of visible area)

This would still make it difficult to work around the edges of a canvas. Every visual editor I know of lets you start drawing from the outside, inwards. There's several use cases where you'd want to do this. The canvas boundary generally only defines what's displayed, not what's being edited.
