### ISSUE TITLE
Default Zoom value

### ISSUE THREAD

**Issue by matteoraggi** [viliusle/miniPaint#18]
How to set the Zoom by default at 50% instead of the actual 100%?

**Comment by viliusle** [comment]
You can use "-" key or Ctrl+mouse wheel scroll to change zoom. There are no way to save zoom for next session.

**Comment by matteoraggi** [comment]
If the Zoom is starting from 100% by default, is really impossible to make it start from 50% by default?

**Comment by matteoraggi** [comment]
But if that 100% is defined by default, theoretically it is also possible to change it into the code, to make that instead of 100% it will be 50%,. I can't understand how it can be impossible.

**Comment by viliusle** [comment]
i can change it to make it be 50% but do all people want it? I think not. 
But I think i understand what you mean, you want to open big image and app should fit it all in the screen, right? That sounds right and i will probably implement it. If it is not what you mean, please describe your problem.

**Comment by matteoraggi** [comment]
I am customyzing your code to open only images bigger of the typical screen, because the dimension is around 1920z1080 pixel, so if I set by default the zoom to 50%, then the users will not be bored to zoom out each time they use miniPaint.

**Comment by viliusle** [comment]
fixed.
