### ISSUE TITLE
[Improvement] High res icons

### ISSUE THREAD

**Issue by donotos** [viliusle/miniPaint#187]
Hi. I just installed miniPaint and i already love it!

One of the first thing i found that needed an improvement is the low res icons. It's all blurry on my monitor.
Maybe you could upgrade to svg files?

Thanks.

**Comment by viliusle** [comment]
Hi, agree, but hardest part is to get these svg or at lest 2x resolution images. When there will be time, i will try to find svg icons.

**Comment by donotos** [comment]
Well if it's only that, i can find them, at worst i'll do them myself...

**Comment by viliusle** [comment]
It would be nice. You can drop svg files here.

all required icons: https://github.com/viliusle/miniPaint/blob/master/images/sprites.png
p.s. gradient icon could be better, but i was not able to find better one.

**Comment by donotos** [comment]
wow ok, let's say that i was a little engrossed in finding them....
[icons.zip](https://github.com/viliusle/miniPaint/files/5455069/icons.zip)
there is everything but the "desaturate" icon. i didn't find something nice...
and the minipaint logo of course.
There is multiple choices for most of the icons.

**Comment by viliusle** [comment]
All images are SVG or 2x resolution compressed PNG (gradient, logo coloured, external icon).

Thank you for samples, i used most, but replaced few.

**Comment by viliusle** [comment]
Also pushed to live.
