### ISSUE TITLE
Issue With Image Clipped to Layer Below and Shadow

### ISSUE THREAD

**Issue by marisalerin** [viliusle/miniPaint#192]
Using layers -> composition -> source atop, I clipped an image to a rectangle layer located below. When I add a shadow to this rectangle layer, the shadow affects what the top image is clipped to. 

Here is a quick video of the issue: https://imgur.com/BCJnVeH

**Comment by JordanMagnuson** [comment]
I've also run into this issue. Shadows should not affect clipping masks.

**Comment by viliusle** [comment]
Shadow is effect and it becomes part of image, and composition is applied to whole layer, so it looks everything fine to me. 

Even i understand you, i don't want to create exceptions here.

**Comment by JordanMagnuson** [comment]
Thanks for the reply. Look at the default behavior in every other major image editor though: Photoshpo, GIMP, etc. They do not clip to the shadow in this situation. Working with graphic designers, I can say the reason why: it is very common to clip to a basic shape, with a shadow--and almost always the desire is to clip to the shape only--it's much more unusual to want to clip to the shadow as well as the basic shape. 

If the designer wants to clip to the shadow, then the shadow can be combined into a single raster image with the shape, and it's not a problem. But currently it's a big problem if the designer does not want to clip to the shadow (the normal use case)--how can they avoid that, when the shape has the shadow applied?

Based on the default behavior in other major image editors, I really hope you will reconsider this issue. Thanks!

**Comment by kmanaseryan** [comment]
@viliusle I think we can close this ticket
