### ISSUE TITLE
[Bug] When adding a gradient on top of brush tool, get unexpected result.

### ISSUE THREAD

**Issue by Giwayume** [viliusle/miniPaint#201]
![image](https://user-images.githubusercontent.com/4075314/100550166-0ea92e00-3246-11eb-939f-07fdacdcabe3.png)

Sample file:
https://ufile.io/1lp7o5x7

**Comment by viliusle** [comment]
[Brush.json.txt](https://github.com/viliusle/miniPaint/files/5612757/Brush.json.txt)
Testing json upload
