### ISSUE TITLE
[Feature Request] Module/tool search feature similar to OS X Spotlight or Blender.

### ISSUE THREAD

**Issue by Giwayume** [viliusle/miniPaint#204]
One problem I consistently have working in Photoshop/GIMP is finding things in menus, or even finding the correct icon to switch to a specific tool. The same problem exists in miniPaint, but to a lesser degree due to having less functionality crammed in its menus. Nevertheless, I think it would benefit from having a quick search (usually F3 key) that lets you type the name of a menu module or tool, and either runs that module or selects that tool. This helps for those brainfart moments when you're having trouble finding something by scanning the list, even when you know it's there. It would also help new users who don't necessarily understand all of the functionality miniPaint has to offer and can search to see if it exists.

Blender solves this problem wonderfully with a little popup that appears next to your mouse when you press F3.

![image](https://user-images.githubusercontent.com/4075314/100682763-ce7ca500-3344-11eb-8fe6-e09343dae39f.png)

A similar pattern exists in OS X for finding applications (CMD + SPACE)

![image](https://user-images.githubusercontent.com/4075314/100682743-c6246a00-3344-11eb-8f2b-51c904b788c0.png)

Photoshop has the "Discover" panel which is similar functionality

![image](https://user-images.githubusercontent.com/4075314/100683380-40092300-3346-11eb-98bd-73dc147e9baa.png)

**Comment by viliusle** [comment]
It would be nice feature, and it is not hard to implement it, because all parts already exists in code, just not in 1 place.

Just small problem: how to tell people that there is such feature, and you can use it... Search icon after logo, or after menu?

**Comment by Giwayume** [comment]
> Probably search icon after menu would work well.

My thoughts, yeah.
