### ISSUE TITLE
Import local font request

### ISSUE THREAD

**Issue by Zoombie008** [viliusle/miniPaint#217]
Hi dear
first of all, thank you for your best project,
can we use import local font or import from google font ?
it's not support with my font  language 

regard

**Comment by viliusle** [comment]
We do not support it.

**Comment by Giwayume** [comment]
Google fonts is still a todo from #185. 

Unfortunately I'm very busy right now since I'm moving.

**Comment by viliusle** [comment]
Closing as duplicate. You can subscribe to #185 to get notified when it will be done.
