### ISSUE TITLE
Glitch with pen and inspect element

### ISSUE THREAD

**Issue by pillows** [viliusle/miniPaint#22]
It's hard to explain but whenever I would inspect element and have the pen tool selected, I would draw on the canvas without needing to hold a mouse click.

Steps to reproduce:
1. Have pen tool selected. (Haven't tried with other tools)
2. Right click and do inspect element on any part of the page.
3. Use your mouse and hover over the canvas.

You will notice that the pen will be drawing with no mouse clicks.

**Comment by viliusle** [comment]
I can not reproduce it. Do you have problems only with inspector? If yes its low priority, but anyway i can fix it only if i can see it.

**Comment by pillows** [comment]
I'll just leave this here (video reproduction):

https://www.youtube.com/watch?v=mkDmTODU5eg

But I agree this is low priority compared to other features/bugs. Not many people would be able to replicate this.
