### ISSUE TITLE
mousedown on canvas is not matched with mouseup outside canvas.

### ISSUE THREAD

**Issue by vishalbiswas** [viliusle/miniPaint#222]
Steps:
1. Select Brush tool
2. Hold left click on white canvas area and drag the mouse outside of the canvas are while holding. This generates a mousedown event inside the canvas area that we process.
3. Release once outside the white area. This generates a mouseup event outside the canvas area that we ignore.
4. Now, try click and release the left mouse button anywhere inside the canvas area. It should create a dot.
5. Then try to draw a line from any other point. You will find that the dot in **Step 4** gets joined to the point where you clicked in this step.

Here's a video of me running the above steps.

https://user-images.githubusercontent.com/7733255/104849657-f2a23e80-5910-11eb-99d2-5fa2b2129545.mp4

**Comment by Giwayume** [comment]
Pretty much the same issue as #176, different flavor.
