### ISSUE TITLE
Clipping Mask No Longer Works After Recent Update

### ISSUE THREAD

**Issue by marisalerin** [viliusle/miniPaint#225]
I had been using Layers --> Composition --> source-atop to "clip" one layer to the layer below it. I can no longer get this functionality to work. I have created a short video of me trying to get this to work, and also a short clip from Photoshop to show what I'm talking about, and what used to happen when I chose the "source-atop" option. 

Please let me know if you need any further clarification. Thank you!

https://imgur.com/YpMKzEb

**Comment by viliusle** [comment]
I can not find any issues, sorry. In your example you had 2 layers using source-atop, and i am not sure what should be correct behavior in this case.

I believe this is what you want? First and second layers have default composition. Thirst layer (star) has source-atop.

[example.json.txt](https://github.com/viliusle/miniPaint/files/5882691/example.json.txt)

**Comment by viliusle** [comment]
> No Longer Works

Do you remember when it was working fine for you? -You can access old versions here: https://github.com/viliusle/miniPaint/releases

**Comment by marisalerin** [comment]
I have a note that it was working on November 11, 2020, which would be
version v4.3.0

I'll try to check through the older builds to see if I can find where it
stopped working.

**Comment by viliusle** [comment]
I checked 4.3.0 and i don't see any issues. Did you tried my example? also are you using https://viliusle.github.io/miniPaint/ or custom build?

It would be good if you give instructions how to reproduce it plus what is wrong and what should be good result?

**Comment by marisalerin** [comment]
Thanks so much. I was getting some other errors and tried a new browser
with a clean cache and had no issues. So I guess the real issue is getting
the cache to clear.

Sorry about that!
Marisa

**Comment by viliusle** [comment]
Understood.
