### ISSUE TITLE
Rotation doesn't work

### ISSUE THREAD

**Issue by karol11** [viliusle/miniPaint#232]
**Platform:**
Chrome, Windows 10

**Steps**:
Paste new image Ctrl+V
Image->Rotate

**Actual result**:
Nothing happened,
Log message:
Uncaught TypeError: c.default.Actions.prepare_canvas_action is not a constructor
    at e.value (bundle.js:56602)
    at e.value (bundle.js:56602)
    at e.on_finish [as onfinish] (bundle.js:56602)
    at e.value (bundle.js:1)
    at HTMLButtonElement.<anonymous> (bundle.js:1)

**Repro** 100%

**Comment by Giwayume** [comment]
Type-o, "Prepare_canvas_action", "P" should be capitalized.

https://github.com/viliusle/miniPaint/blob/master/src/js/modules/image/rotate.js#L164

**Comment by viliusle** [comment]
Thank you, will fix it soon.
