### ISSUE TITLE
Best way to save an image in an HTML form? Or: Is there an onChange event?

### ISSUE THREAD

**Issue by flange-ipb** [viliusle/miniPaint#237]
Hello,
first of all thanks for creating such an advanced image editor!

I'd like to integrate miniPaint into an HTML form and write its data into a hidden input field. The [open-edit-save example](https://github.com/viliusle/miniPaint/blob/4eb75b3b26c57d2960a898c4ea643bda73dad6a2/examples/open-edit-save.html#L86) shows nicely how data can be written.
My question: When to do this?
- Does miniPaint offer an onChange event that listeners can register to? How would the performance be if I call `miniPaint.FileSave.export_as_json()` in such a callback? (That's usually my favorite strategy because of the web application framework I use.)
- Hook some JS snippet to the submit button's onclick or to the form's onsubmit that copies the data before form submission. (I guess `export_as_json()` is synchronous.)

Any suggestions/ideas?

Best regards,
Frank

**Comment by viliusle** [comment]
If you are using form, you can even save state just before form submit ...

**Comment by flange-ipb** [comment]
Ok, thanks!
Solution 2. or 3. work nicely.
First, I tried to put the exported JSON data into an `<input type="hidden">`, which seems to have the same content size limitations like `<input type="text">` - thus, large images cannot be sent. I managed to send the data [embedded in a Blob object ](https://stackoverflow.com/a/66466544) via a `<input type="file">` now.
