### ISSUE TITLE
Implement border/stroke tool as effect that is linked to the layer it was applied to

### ISSUE THREAD

**Issue by JordanMagnuson** [viliusle/miniPaint#240]
Tools -> Borders

Issue #1: border applies to entire canvas, rather than the selected layer: https://i.imgur.com/YYYyBWX.png

Issue #2: border is created on new layer, which means that when you move the original layer (the layer the border was applied to), the border stays behind. One solution to this would be to simply make it possible to move multiple layers at once (e.g. by shift-selecting layers). Though ideally the border would be linked to the original layer it was applied to, in a similar way that shadows are (so when you move the base layer, the border is automatically moved with it).

**Comment by viliusle** [comment]
This is just simple way to create border for all canvas. Advanced borders can be created manually using rectangle shape. I see this request as low priority or rejected.

p.s. I am trying to keep this app small, simple and useful.  We can not have all features, it would become Photoshop ...

**Comment by JordanMagnuson** [comment]
Thanks for the reply! In my opinion the border/stroke tool is actually one of the more useful/simple tools in an image editor. My team and I are actually working on making a stripped-down, simpler version of miniPaint, based on feedback from a large number of users from our digital scrapbooking site--and the border/stroke tool is one of the most-requested tools, along with drop-shadow (a very typical use case is that people want to bring in a photo, and add a border and drop shadow around the photo). 

So I would ask you to reconsider, but thanks for your time in any case! 

(I think ideally the border/stroke tool would work similarly to the drop-shadow tool, adding an "effect" to the current layer that would move with it, rather than adding a completely new layer.)

**Comment by viliusle** [comment]
>one of the most-requested tools

interesting... Can you share some of these top requests?

Maybe it is possible to convert to non-destructive effect. It could work.

**Comment by JordanMagnuson** [comment]
Thanks for the reply. The feedback has been gathered over several years in conversations with users on our site (our site is DigitalScrapbook.com, which we have been running for over 10 years now). 

You can get a general feeling for the layouts that our users create by browsing our gallery at https://www.digitalscrapbook.com/browse/layouts

We have almost 90,000 user-created layouts that have been uploaded there, and you can see that a very large percentage of them make use of a border/stroke around the photos or other elements. (A typical use case for our users is to bring in a "kit" of pre-created images, then add their own text and photos. They do little manipulation of the images beyond rotating/scaling, and adding drop shadows and stroked borders around items and photos). 

A few simple examples that I pulled from the front page:

- https://www.digitalscrapbook.com/michelle-belisle/gallery/memories-in-waskesiu-layout-travel-blue
- https://www.digitalscrapbook.com/becky-wooler/gallery/january-2021-week-4-layout-apr-2021-challenge-blog-train-yellow-mint-green
- https://www.digitalscrapbook.com/cindy-taylor/gallery/doilies-layout-gingerscraps-purple-pink-beige
- https://www.digitalscrapbook.com/sarah-evans/gallery/rhino-layout-animals-apr-2021-challenge-template-green-gray-brown
