### ISSUE TITLE
[Feature Request] Start with "fit to screen" on large canvas creation.

### ISSUE THREAD

**Issue by JordanMagnuson** [viliusle/miniPaint#243]
When a new canvas is created (File -> New), the app defaults to leaving it at 100% zoom. Which isn't great for very large canvases.

Instead of 100% zoom, would be nice to "fit to screen" as soon as a new canvas is created. (Equivalent to hitting the "fit" button in on the preview window pane): https://i.imgur.com/ejZcDzf.png

**Comment by viliusle** [comment]
That is nice idea and easy to implement.
