### ISSUE TITLE
Regular Expression DoS vulnerability

### ISSUE THREAD

**Issue by linci8210** [viliusle/miniPaint#247]
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected 1 vulnerable regex(es) from your repository.

1: ``url\s*\(((?:[^)(]|\((?:[^)(]+|\([^)(]*\))*\))*)\)`` in miniPaint/dist/bundle.js

Please try the following:

	var pattern = "url\\s*\\(((?:[^)(]|\\((?:[^)(]+|\\([^)(]*\\))*\\))*)\\)";
	var input = "url((\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b";
	var re = new RegExp(pattern);
	var matched = input.match(re);

We didn’t create a pull request because we're not sure if these cases are possible to take place in your program, we also do not understand the functionality of these regexes as you do. Thank you for your understanding.

**Comment by Giwayume** [comment]
There's no backend in this application, this does not apply.

**Comment by viliusle** [comment]
It will still appear in old dist/* files, but will be gone after next version update.
