### ISSUE TITLE
Selection tool circular

### ISSUE THREAD

**Issue by Zakaria1854** [viliusle/miniPaint#25]
Hi, I liked it very much. It's a complete photoeditor. Can you add the circular selection tool. Right now it has the square selection tool.

**Comment by viliusle** [comment]
Hello, ok, i will add it to todo.

**Comment by sajangrg** [comment]
With the selection tool, one can resize it. What if one could somehow rotate it as well. I actually need. Thank you!

**Comment by viliusle** [comment]
Selection can be moved to separate layer and rotation can be done here. For now.

**Comment by viliusle** [comment]
Use Clone tool to achieve similar functionality for circular select. Probably wont be implemented.
