### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by msvp** [viliusle/miniPaint#250]
Hello  from France !

I've installed miniPaint behind Nginx.

All is working correctly except the translation : 
![image](https://user-images.githubusercontent.com/5102015/115041892-481bc680-9ed3-11eb-8a40-e47041270e7e.png)

No error in the console.

Any Idea ?

Thanks !

**Comment by viliusle** [comment]
try with latest code please, it was updated  yesterday.

**Comment by msvp** [comment]
Perfect !

Many thanks for that Work !
