### ISSUE TITLE
[Docs] Update iframe examples to add feature policy for camera access

### ISSUE THREAD

**Issue by Giwayume** [viliusle/miniPaint#251]
This is one of many files that show how to instantiate minpaint on another page using an iframe:
https://github.com/viliusle/miniPaint/blob/master/examples/add-edit-imgData.html#L4
I don't know the list of all files that show iframe usage examples.

When the user does `File -> Open -> Open from Webcam`, this feature has usage limiations. [By default access to the webcam from iframes is not allowed](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#feature_policy).

For iframes that need this access, need to add `allow="camera"` to the iframe declaration.

```
<iframe allow="camera"></iframe>
```

**Comment by viliusle** [comment]
I will update examples.
