### ISSUE TITLE
Suggestions? : Rename layers.

### ISSUE THREAD

**Issue by sajangrg** [viliusle/miniPaint#26]
When multiple layers are created, I think everyone gets confused while selecting one particular layers back. Is it possible to make layers rename on double click or in any other ways?

**Comment by viliusle** [comment]
When you select some layer, you see shake effect on content. It help a little.
But yes, i agree, and "rename" feature is already in my todo list and will be added in future.

**Comment by sajangrg** [comment]
It would be wonderful if you'd add it sooner. Thank you for the response.

**Comment by viliusle** [comment]
Layers rename added with menu or using double click.
