### ISSUE TITLE
[Feature Request]  Allignments and layer lock

### ISSUE THREAD

**Issue by mykael25** [viliusle/miniPaint#260]
Hello good day maam and sir's thank you for this web application, i would like to request layer locking and object alignment options help would be much appreciated thank you and god bless

**Comment by viliusle** [comment]
**About alignments**: we already have guides and snap feature.

Locking layer would be nice to have on day.

p.s. multiple request should be created using separate tickets.

**Comment by mykael25** [comment]
Once again Thank you sir for this superb program, i know and i like the snap feature of this web application as well as the guides but what i am trying to say is the alignment options of the objects such as this 
![image](https://user-images.githubusercontent.com/56788929/127272633-a097ed89-8b72-4c56-81d1-9e935df214c5.png)
it would be pretty handy when managing object alignments if this feature is present as well as for accuracy purposes, but overall what a great web application it sure helps alot god bless :) 

p.s sorry for the multiple request on one  ticket
