### ISSUE TITLE
Selection tool not working since release 4.4.0 and actual versions ?

### ISSUE THREAD

**Issue by redgriffith** [viliusle/miniPaint#268]
Hello
Since v4.4.0, "Selection" tool not working ? I can trace the green square but can't cut élément...
(tool is ok for 4.3.1 and before).

thanks

**Comment by viliusle** [comment]
Hello,
There is "delete selection" and "copy selection".
Looks like "cut" (copy to clipboard and remove) - was removed, sadly I can not remember exact reasons now.

**Comment by redgriffith** [comment]
thanks i see, i need to go to "edit" section.
