### ISSUE TITLE
[Feature Request] resize/rotate/transform selection

### ISSUE THREAD

**Issue by cailiang9** [viliusle/miniPaint#269]
like in mspaint , this is a high frequent feature.
Although there are copy selection(will generate a new layer) and del selection, you can only perform one operation and then the selection disappeared.
You can not use del+copy selection and then transform your new layer. And it is unintuitive to user.

**Comment by viliusle** [comment]
I believe if you want to edit selection, it would be better to copy it to separate layer and from this point do anything you want. It is more flexible and not destructive editing. And it makes things for developer much more easier not duplicating layers features on selection.

Su I guess answer is no,
