### ISSUE TITLE
Exporting image as bmp on Chrome/Edge/Opera causes error

### ISSUE THREAD

**Issue by senaiboy** [viliusle/miniPaint#274]
As per title.

Error bubble "Your browser does not support this format" shows up when choosing to export image as bitmap (.bmp). Is this a bug?

**Comment by viliusle** [comment]
It is not a bug. Exporting as BMP works only on Firefox, other browsers does not support exporting canvas as BMP.

You should not use BMP anymore (there are much better formats), but if you must, you can switch to Firefox and generate it.
