### ISSUE TITLE
Function integration

### ISSUE THREAD

**Issue by Gabri3I3** [viliusle/miniPaint#283]
Hello! 

Thanks to Vilius for creating and sharing this wonderful tool. I will almost certainly use it on my own project.

I wanted to ask you if it was possible to integrate some functions:
• Offer the possibility of making a round selection
• Invert selections to allow users to clear the outside of the selection.
• Use google fonts
• Add images, shapes and templates predefined by the site administrator. For example by creating a predefined folder ../background/ ../stikers/ ../shapes within my installation

Finally, how do I get the program to start with other default settings: template, language and brush colors?

For these changes I can evaluate a payment.

Thanks everyone for any answers!

**Comment by viliusle** [comment]
>Use google fonts

It is already implemented: left sidebar > Text > top tools > font > add font > [search]

**Comment by Gabri3I3** [comment]
Thank you very much! 👍
Can you help me with other implementations too?

**Comment by viliusle** [comment]
>Finally, how do I get the program to start with ... language ... ?

Append "lang" in URL. For example https://viliusle.github.io/miniPaint/?lang=de
If you want to change other parameters, you can change it here https://github.com/viliusle/miniPaint/blob/master/src/js/config.js, but you will need to rebuild project: https://github.com/viliusle/miniPaint/wiki/Build-instructions

**Comment by viliusle** [comment]
Custom selection would take much more effort, I do not think it will happen.
You can not integrate your custom images, but there are ability to search for images and add it (left sidebar > Search image)

Sorry, but I do not customize it for specific usage, I try to implement useful features for everybody.

**Comment by Gabri3I3** [comment]
Thanks again, could you tell me a programmer who can make these changes for a fee?

**Comment by viliusle** [comment]
Can not help you.

**Comment by Gabri3I3** [comment]
Thanks

**Comment by Giwayume** [comment]
Try a site like upwork.com if you're looking to hire someone.
