### ISSUE TITLE
Support for a new template

### ISSUE THREAD

**Issue by saidinesh5** [viliusle/miniPaint#284]
Would you be interested in accepting a pull request for a template that:

1) Is of dimensions: 480x240
2) Saves and opens LOGO.ME files (which are basically just RGB24 image)?

This file is used as startup logo for a certain product, and currently they just distribute an ffmpeg command to convert bmp to rgb24. I patched [my fork of mini paint](https://github.com/viliusle/miniPaint/compare/master...saidinesh5:master) to support it instead. This way, that i don't have to drop down to CLI every time i want to change the logo. 

This is a very niche usecase, but since RGB24 is a useful format for other cases like this, I thought to share the changes back and see if you'd be interested.

**Comment by viliusle** [comment]
I do not want to do this because as you said "This is a very niche usecase" for both cases.

>This way, that i don't have to drop down to CLI every time i want to change the logo.

Create a rebuild.bat file with instructions to go to directoryand rebuild miniPaint. Once you do it, next time you should be able to run it without CLI, but only clicking on that file.

**Comment by saidinesh5** [comment]
Oh no worries. I already have the site with my changes running on my GitHub pages.

Just wanted to see if any of the rgb24 related changes would be useful for you.

Regards,
D
