### ISSUE TITLE
Suggested improvements to "rotate layer" handle

### ISSUE THREAD

**Issue by JordanMagnuson** [viliusle/miniPaint#286]
Currently when a layer is smaller than x and the view is sufficiently zoomed out, the rotate handle is hidden. Presumably because there is not enough space to show it. 

Testing in Firefox and Chrome, it seems that there is still plenty of space to show the rotate handle in most of these situations (especially because the middle transform handles are already hidden for very small layers). Perhaps the position of the rotate handle can just be moved slightly, and it can be shown on smaller layers / more distant zooms?

Short video demonstration: https://www.loom.com/share/03d51ee8d4014ccdb6f9e05f40483a22

**Comment by viliusle** [comment]
I agree, limits when it disappear should be checked and updated.

**Comment by JordanMagnuson** [comment]
Another, related improvement: the rotate handle should change position depending on where a layer is on the canvas, so that it is always accessible, if possible. Currently, if you move a layer e.g. to the upper-right hand corner of the canvas, you can no longer access the rotate handle. 

![image](https://user-images.githubusercontent.com/436794/153238372-30b0fd47-cab7-4b36-aa0e-5a6257d278e5.png)

**Comment by kmanaseryan** [comment]
> Another, related improvement: the rotate handle should change position depending on where a layer is on the canvas, so that it is always accessible, if possible. Currently, if you move a layer e.g. to the upper-right hand corner of the canvas, you can no longer access the rotate handle.
> 
> ![image](https://user-images.githubusercontent.com/436794/153238372-30b0fd47-cab7-4b36-aa0e-5a6257d278e5.png)

@JordanMagnuson it's possible but it requires a bit more time. Created a PR for the original issue, if you want to make this change let me know, but it requires quite some time to finish.

**Comment by JordanMagnuson** [comment]
> @JordanMagnuson it's possible but it requires a bit more time. Created a PR for the original issue, if you want to make this change let me know, but it requires quite some time to finish.

@kmanaseryan Okay, let's create another issue for that functionality, then, and put it on hold for now.

**Comment by viliusle** [comment]
>Another, related improvement: the rotate handle should change position depending on where a layer is on the canvas, so that it is always accessible, if possible. Currently, if you move a layer e.g. to the upper-right hand corner of the canvas, you can no longer access the rotate handle.

Separate issue - #294
