### ISSUE TITLE
Suggestions?: Image/text cuts off.

### ISSUE THREAD

**Issue by sajangrg** [viliusle/miniPaint#29]
When image/text is moved beyond the borders of workspace and again moved inside, the image/text portion that crossed the borders disappears. Only the portion remaining inside remains. Is there any way to prevent the image/text from cutting off?

**Comment by viliusle** [comment]
If you want to leave invisible part available for future, it still be gone after saving it anyway. Saving it should create performance issues . We can live without it i believe.
If you want this only for session only, can you make layer copy? 
If you just lost image data, remember - there is 3 level undo, so using ctrl+Z will help you.
