### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by anonimo82** [viliusle/miniPaint#290]
The App's GUI sometimes doesn't fit the viewport.
Make it scroll when this is the case.

**Comment by viliusle** [comment]
Are you trying miniPaint on very small screen? Which part does not fit, can you attach screenshot?

**Comment by anonimo82** [comment]
I'm attaching a screenshot.
The effects menu overflows the screen.
No, I have a QHD resolution. 
![Screenshot_20220212-052512_PhotoEditorPlus](https://user-images.githubusercontent.com/38261009/153696452-0e255fb6-10ba-4133-ae95-73fc041f3a7f.jpg)

**Comment by Giwayume** [comment]
@anonimo82  This issue was fixed a year ago, you need to update from master.
