### ISSUE TITLE
Alpha edit

### ISSUE THREAD

**Issue by anonimo82** [viliusle/miniPaint#291]
When layering photos (in eg. when you're making montage) is useful to create an alpha mask for the pic you're working with.

**Comment by anonimo82** [comment]
By the way, may be also being able to edit a single channel (1 to 4 of RGBA)

**Comment by viliusle** [comment]
This looks rare use case, adding this to TODO list with very low priority also does not makes any sense. So I guess this will not be implemented, unless somebody will push PR.

But thank you for suggestion.
