### ISSUE TITLE
Possible?: Saving file in PDF format.

### ISSUE THREAD

**Issue by sajangrg** [viliusle/miniPaint#30]
Is it possible adding the feature to save the file in PDF format as well?
Saving in JSON format, it doesn't bring back any saved layers when it is open back. It is supposed to bring back the saved layers back to the workspace, right?

**Comment by viliusle** [comment]
using JSON  format should bring everything back, including layers. If it does not work for you, can you give more details? (separate issue please) It works perfect for me.

PDF can be added, but PDFs for documents usually, not for images. Do we really need it? There should be no import of course. And what to do with layers.

**Comment by sajangrg** [comment]
It is alright if it would be saved it PDF format. When the saved PDF file is opened it should open as saved it PNG format. Of course we cannot import back.

**Comment by viliusle** [comment]
JSON problem fixed, PDF will not be implemented, because it would require some library, would be used rarely, pdf is not related to images and there are converters (like classic "print to pdf").
