### ISSUE TITLE
Possibility to import/export svg files

### ISSUE THREAD

**Issue by FabianMauz** [viliusle/miniPaint#303]
First of all, thank you for this great project.

Is it possible to import svg files in such a way that the groups within the svg file are converted into their own layer?
When exporting, the individual layers would then be converted into their own group.

Kind regards and best wishes.

Fabian

**Comment by viliusle** [comment]
Hardly,  minipaint and SVG use different formats.

**Comment by Giwayume** [comment]
There are open source web based svg editors out there

https://svgedit.netlify.app/editor/index.html

While minipaint uses some svg drawing techniques internally for things like brushes, ultimately it is a raster editor right now.
