### ISSUE TITLE
Half of exported image is gray if source-atop is used

### ISSUE THREAD

**Issue by David-Development** [viliusle/miniPaint#304]
Over the past month I've followed the discussion around the broken `source-atop` behavior closely however from what I understand it is fixed in the latest "master". Therefore I tested it locally and it works great in the editor. However, exporting images breaks them (left is the editor, right is the exported image). Note that you can see the "mask" rectangle on the bottom half of the screen.

<img src="https://user-images.githubusercontent.com/4489723/158382841-8f50d934-17ba-45ef-b16e-cc47e8db77c7.png" height="600px" /> <img src="https://user-images.githubusercontent.com/4489723/158382856-7e2ee639-644f-4ff8-90ea-e59f2f2e4d79.png" height="600px" />

Example Template that reproduces the issue: 
[sample.json.zip](https://github.com/viliusle/miniPaint/files/8253462/sample.json.zip)

Thanks for all the great work on this tremendously useful tool!

**Comment by Giwayume** [comment]
This is just a simple width/height mixup. Your monitor height probably doesn't surpass the width of this image (1440px) in the lower resolution viewport preview so the bug only shows up when the full size image is exported.

**Comment by viliusle** [comment]
Fixed on master branch.
