### ISSUE TITLE
Fix Arabic typing Problems

### ISSUE THREAD

**Issue by bloogtricks** [viliusle/miniPaint#307]
Arabic letters are not joined together
![Screenshot 2022-03-24 at 01-41-52 miniPaint](https://user-images.githubusercontent.com/30641543/159815506-804e29cc-5be0-4a0c-8b06-2fba3a66264e.png)

**Comment by Giwayume** [comment]
I don't know much about arabic, but if you trying to type right to left that's not coded right now.

**Comment by Giwayume** [comment]
Ok, this is an extremely complicated problem to solve. It involves implementing bidirectional runs of text, and being able to detect the bidi class of a unicode character. There's also a ton of logic around joining letters. 

I seriously doubt I'll have the mental capacity to tackle this, but here's the spec if anyone is interested.

https://www.w3.org/TR/alreq/

**Comment by viliusle** [comment]
>Ok, this is an extremely complicated problem to solve

In this case, lets use our time on higher priority tasks.
