### ISSUE TITLE
Suggestions?: To change canvas size

### ISSUE THREAD

**Issue by sajangrg** [viliusle/miniPaint#31]
I have used the "size" feature under Image menu to change the canvas size. Its good to have that feature. Is there anyway I can edit the value or something else in the code to change the size of the canvas as default?

**Comment by viliusle** [comment]
Try to use File -> New. It will list common resolutions. Maybe i should list it in Image > Size ...

I can also save entered size in file>new and auto load it on next page refresh. But this will remove current functionality when app use max possible resolution that fits into window.

Another idea is to add extra resolution like "last used" if above does not help.

**Comment by sajangrg** [comment]
Now the workspace has 640px(width) and 480px(height), when we open it, right? So, what if I want the workspace to be 3600px(width) and 5400px(height) when it opens for the first time itself (without using "File > New" or "Image > Size" in the menu) ? I was unable to find the code to change the value, could you please, tell me where is it?

**Comment by viliusle** [comment]
file: main.js
function:  init() on line 16  - GUI.autodetect_dimensions();

**Comment by viliusle** [comment]
implemented ability to save dimensions (file-new)
