### ISSUE TITLE
Question: What is "Content fill" for?

### ISSUE THREAD

**Issue by anonimo82** [viliusle/miniPaint#310]
As in subject, what is "Content fill" used for?

Thanks for any help

**Comment by viliusle** [comment]
It is used if you have image and you want to fit it to bigger space, but currently it is not working, as I tested today.

Looks like need fixing.

**Comment by anonimo82** [comment]
I see, thanks

**Comment by viliusle** [comment]
Do not close, till it is fixed.

**Comment by anonimo82** [comment]
Oh, ok. Sorry. Did you reopen it already?

**Comment by viliusle** [comment]
>What is "Content fill" for?

Demonstration:

Before:
![before](https://user-images.githubusercontent.com/3708786/211216820-6f9e71ed-5170-4933-b434-48b84a657030.jpg)

After:
![after](https://user-images.githubusercontent.com/3708786/211216854-796a7081-749a-4ea8-a6ad-104c3860942e.jpg)
