### ISSUE TITLE
Shapes - Less is more

### ISSUE THREAD

**Issue by anonimo82** [viliusle/miniPaint#311]
Instead of offering the option to draw triangles, pentagons, stars, etc, just offer to draw arbitrarily sided polygons, with optionally rounded corners, with in/out-setting vertices, with minimum 3 sides.
Maybe also provide a separate X and Y scale to distort the shape and 2 radius values (inner and outer) for round corners

This way, user could draw:
- Stars
- Polygons
- Triangles
- Squares
- Rectangles
- Circles
- Ellipses
- Flowers 

All with a single tool

Something **similar** to this: https://youtu.be/gYSzHfjhtnU but not really the same

Thanks for anything

**Comment by anonimo82** [comment]
@viliusle anything?

**Comment by viliusle** [comment]
I would like polygons, it is good idea, but I would probably leave these shapes as is.

**Comment by anonimo82** [comment]
Do you mean you're willing to add polygons sideways, or aren't you going to do that at all?

**Comment by viliusle** [comment]
My plan is to add polygons, but leave shapes as is (do not remove it).

**Comment by anonimo82** [comment]
Wow, thanks so much

**Comment by anonimo82** [comment]
Any update?

**Comment by viliusle** [comment]
What is left:

- Polygons
- Bézier curve
- quadratic Bézier curve
