### ISSUE TITLE
Gaussian Blur changes with zoom level

### ISSUE THREAD

**Issue by zhaohanfeng** [viliusle/miniPaint#314]
When apply Gaussian blur effect to an image, the blue effect on the final saved image is not as seen on the editor if the zoom level is not 100%. The blur effect changes with zoom levels.

**Comment by zhaohanfeng** [comment]
Another issue is that the preview image in preview pane is not clear for blurred images

**Comment by viliusle** [comment]
I see all issues. thank you for report.
