### ISSUE TITLE
Chinese input is not supported

### ISSUE THREAD

**Issue by tanjie123** [viliusle/miniPaint#318]
Lots of errors when editing canvas with Chinese text

**Comment by tanjie123** [comment]
`[](url)`

**Comment by Giwayume** [comment]
What are the errors? It appears to accept them when copy/paste. But depending on what you're using to input, I wouldn't expect the character previews to show if you're using IME, for example, to phonetically enter them.

![image](https://user-images.githubusercontent.com/4075314/167417146-71f458e3-ef5a-4b4f-ade8-4f2d95da5bd5.png)

**Comment by viliusle** [comment]
Closing becouse: missing information / can not reproduce.
