### ISSUE TITLE
Lines

### ISSUE THREAD

**Issue by anonimo82** [viliusle/miniPaint#321]
Please, add a way to draw straight lines, may be in sequence too

Thanks for any help.

**Comment by viliusle** [comment]
You can draw straight lines: left tools menu > shapes > lines.
If you want sequence, you can draw 1 line, after mouse release don't move mouse and start drawing second line, it will act similar to multi line.

**Comment by anonimo82** [comment]
Ok, it's not very comfortable with touch screen, but should work.
Thanks
