### ISSUE TITLE
[Feature Request] Add editable charts

### ISSUE THREAD

**Issue by marcpre** [viliusle/miniPaint#327]
Hi,

I love miniPaint. Its well build and extremely powerful.

If you add editable charts it would make the application even more powerful.

User Stories:
1. As a user I can select a chart. (similar to the forms menu)
2. I can add the chart and edit the data in the chart
3. The chart is saved in the miniPaint json format with the data rows.

Happy to help and support wherever I can.

Kr

**Comment by viliusle** [comment]
Hello,
There are lots of charts types, options and implementing charts would take lots of time and not much people would benefit from it. 

It would be best for you to generate charts using exiting application (for example Microsoft/Google Excel) and import it into miniPaint as image.
