### ISSUE TITLE
Import json with shapes does not work

### ISSUE THREAD

**Issue by marcpre** [viliusle/miniPaint#328]
Hi,

I created in the online editor the following image:

![image](https://user-images.githubusercontent.com/30902582/183102653-2c471fb9-ce55-4151-81fe-2fa18f39c61b.png)

I exported it as json:

[banner3.zip](https://github.com/viliusle/miniPaint/files/9269669/banner3.zip)

When I open it again in miniPaint I get this:

![image](https://user-images.githubusercontent.com/30902582/183102888-214bc759-4bc5-4ca8-9eac-47a28bc95e20.png)

Any suggestions why the shapes are not rendered correctly? Also the image-size is not correctly imported from the json.

**Comment by viliusle** [comment]
Hi,
I see that there are few issues:

- if image has negative dimensions, it will not be imported correctly.
- some shapes missing colors

I will try to find time on weekend and fix it.

**Comment by viliusle** [comment]
Fixed, new version released,
