### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Dejin1** [viliusle/miniPaint#330]
How do I assign icons to copied functionalities
![image](https://user-images.githubusercontent.com/35273527/187240621-9eba2bfc-8f0f-4628-bc82-91a250be16d9.png)

As you can see I added buttons under shapes to easily get the most popular shapes how do I assign the icons for these shapes I tried putting the image with the same name in the SVG folder I also tried doing this in the code:

{
		name: 'arrow',
		visible: true,
		**icon: 'arrow.svg',**
		attributes: {
			size: 4,
		},
	},

**Comment by Dejin1** [comment]
![image](https://user-images.githubusercontent.com/35273527/187246756-19d5bf1c-80e4-4a83-93c1-0e4bff79de2e.png)
![image](https://user-images.githubusercontent.com/35273527/187246891-0aab143e-4726-41aa-9d10-79f5c62ea0df.png)

I even tried adding the locations to the CSS file and service worker and updated version

**Comment by Dejin1** [comment]
1. I have done that
2. I posted a pic showing I did that in my second post
3. rebuilding is just using this command: npm run dev right?

Here all the pics of everything you suggested

**Comment by Dejin1** [comment]
Ok so im not sure what fixed it..though when added another link to the line as well as changed another part of the layout.css file it must've finally realized that the file was now updated or something so Im good now thanks ;)

**Comment by Dejin1** [comment]
Another question if you dont mind?

How can i make the transparent background of the text draggable. 

Im trying to help older users be able to move the text and if they select a transparent part of the text they cant drag it.

Is there anyway to modify this maybe I can modify the layer background to be 1% opacity or something 

Also thankyou so much for making a wonderful tool is there anyway i can donate to ya ;)

**Comment by viliusle** [comment]
>rebuilding is just using this command: npm run dev right?

Yes, it will do 1 time rebuild, but I recommend you using `npm run server` command for developing. It would constantly rebuild on any file update.
Check https://github.com/viliusle/miniPaint/wiki/Build-instructions 

>How can i make the transparent background of the text draggable.

In this case users should select layer on layers list on right sidebar.

>Is there anyway to modify this maybe I can modify the layer background to be 1% opacity or something

There is. Check is done here: https://github.com/viliusle/miniPaint/blob/master/src/js/tools/select.js#L482 so if you  find invisible text layer, you can set opacity to 100 before check, and restore it after, check would work even with invisible text layers.

**Comment by Dejin1** [comment]
"There is. Check is done here: https://github.com/viliusle/miniPaint/blob/master/src/js/tools/select.js#L482 so if you find invisible text layer, you can set opacity to 100 before it and before .convert_layer_to_canvas(), and restore it after, check would work even with invisible text layers."

so:

//render main canvas
		for (var i = 0; i < layers_sorted.length; i++) {
			var value = layers_sorted[I];
                        var canvas;

                     if(value.opacity == 0)
                     {
                         value.opacity = 100;
                         canvas = this.Base_layers.convert_layer_to_canvas(value.id, null, false);
                     }else{
                         canvas = this.Base_layers.convert_layer_to_canvas(value.id, null, false);
                     }
			

			if (this.check_hit_region(e, canvas.getContext("2d"), value) == true) {
				await app.State.do_action(
					new app.Actions.Select_layer_action(value.id)
				);
				break;
			}
		}

**Comment by Dejin1** [comment]
![image](https://user-images.githubusercontent.com/35273527/187286616-b7ee002d-962a-4e79-b059-1c05bda8f83c.png)

Interestingly this does not post either hit or no hit even when I take off the check for image type

**Comment by viliusle** [comment]
Because this section is for 1000x1000+ size layers, like big images to avoid lag.
For text layers, your hit would be here:
https://github.com/viliusle/miniPaint/blob/master/src/js/tools/select.js#L514

**Comment by MWB6763** [comment]
Warning: off topic with this issue, but can I remake this paint editor, it's really hard having to make a paint editor on my own.

**Comment by viliusle** [comment]
> Warning: off topic with this issue, but can I remake this paint editor, it's really hard having to make a paint editor on my own.

@MWB6763 yes, you can.
