### ISSUE TITLE
ctx.DrawImage() not working

### ISSUE THREAD

**Issue by BenjaminIrwin** [viliusle/miniPaint#331]
Firstly, fantastic work. I'm loving this repo - open source at its best!

I'm trying to add a tool to Minipaint which communicates with an external server. It converts the current image to BLOB, sends it off to a server and receives back a different image in Base64 format (sometimes of different dimensions to the OG image). The tool then replaces the OG image on the canvas with this new image.

Everything seems to be working, the image is received by the server and the response is also received. However, when I draw the image on the canvas nothing happens - the received image does not show up. Note: I have tried console.log(image.src) after assignment and the output is correct (the image received from the server). There are no javascript errors.

What am I doing wrong here? 

```
        var file = this.dataURItoBlob(img); // Convert Base64 image to binary
        var form = new FormData();
        form.append('image', file);
        jQuery.ajax({
            "url": "http://0.0.0.0:8081/test?&param1=" + params.param1 + '&param2=' + params.param2,
            "method": "POST",
            "timeout": 0,
            "processData": false,
            "mimeType": "multipart/form-data",
            "contentType": false,
            "data": form,
            success: AjaxSucceeded
           });
       
        function AjaxSucceeded(response) {
				ctx.clearRect(0, 0, canvas.width, canvas.height);
				var image = new Image();
				image.onload = function() {
					ctx.drawImage(image, 0, 0);// Issue here
				};
				image.src = 'data:;base64,' + response; 
				app.State.do_action(
					new app.Actions.Update_layer_image_action(canvas)
				);

        }
	}
```

Thank you for this legendary repo and any help you can give!

Updated code to remove irrelevant bits.

**Comment by viliusle** [comment]
Look at this code, which does similar thing.
https://github.com/viliusle/miniPaint/blob/master/src/js/modules/file/open.js#L213

I am not sure what is ctx in your example, but on miniPaint, you can not just draw anything, you have to create new layer, in this case with type of image. And miniPaint will render that new layer automatically.

**Comment by BenjaminIrwin** [comment]
Thanks very much. This clears it up. Very grateful
