### ISSUE TITLE
Constraining image dimensions

### ISSUE THREAD

**Issue by BenjaminIrwin** [viliusle/miniPaint#332]
Is there any way to constrain the dimensions of the base layer in minipaint? 

I want to make it so that the underlying canvas is always square in aspect ratio. I want to be able to add non-square images but still make sure `config.WIDTH== config.HEIGHT` at all times. For example: [https://ibb.co/xXRdTXP](url)

If it can't be done easily can you point me to the right alterations in the code? Thanks so much

**Comment by viliusle** [comment]
Menu > image > Canvas size does it, related code: 
https://github.com/viliusle/miniPaint/blob/master/src/js/modules/image/size.js#L93

So you need to build your custom version and modify https://github.com/viliusle/miniPaint/blob/master/src/js/modules/file/open.js functions to keep square in aspect ratio. (search for "Autoresize_canvas_action")
