### ISSUE TITLE
Feature request: Ability to change the image and color of rectangles in the draw editor

### ISSUE THREAD

**Issue by ser-mk** [viliusle/miniPaint#349]
As a user of the draw editor, I would like the ability to change the image and color of rectangles in the editor. Currently, the color of the rectangles is always gray and there is no way to change it. Additionally, the ability to change the image of the rectangle would provide more flexibility and customization options for users. This feature would greatly enhance the functionality and usability of the draw editor.

**Comment by viliusle** [comment]
>As a user of the draw editor, I would like the ability to change the image and color of rectangles in the editor. Currently, the color of the rectangles is always gray and there is no way to change it.

You can set "Fill color" and "Border color" before creating shapes. Once you select which shape you want to draw, look at top toolbar, it will allow you set some parameters, including colors.
Once shape is created, changing color is not implemented yet.

> Additionally, the ability to change the image of the rectangle would provide more flexibility and customization options for users. This feature would greatly enhance the functionality and usability of the draw editor.

If you would create rectangle and change it content to image, it would become just image. You already can do many things on images.

**Comment by ser-mk** [comment]
Thanks for the response. I didn't realize the option for "Fill color" and "Border color" existed before creating shapes. I'll definitely make use of it in the future. Thanks for creating this project.
