### ISSUE TITLE
Contiguous being glitchy

### ISSUE THREAD

**Issue by RepeatGitHub** [viliusle/miniPaint#350]
I've been using miniPaint for a bit, and I noticed that whenever I use the Fill or Magic Erase tool with Contiguous enabled, it applies to pixels that it shouldn't apply to, even with the lowest power on said tools possible.
When using the Fill or Magic Erase tool with Contiguous disabled, it works as intended, so I assume the issue is because of a bug within the Contiguous feature.

**Comment by viliusle** [comment]
Power is in scale of 1-100, not 1-255.
So even with power of 1, it will be 1% or 2.55 color value from 0-255 range.

I agree, it can be confusing.
