### ISSUE TITLE
Suggestion: If the zoom is much high, increase zoom in the thumbnail "view from afar"

### ISSUE THREAD

**Issue by luihumberto** [viliusle/miniPaint#36]
Hello, I have a suggestion that can increase accessibility.

If the zoom is much high, increase zoom in the thumbnail "view from afar", that is, this square:

![image](https://cloud.githubusercontent.com/assets/23081124/19786615/99940cdc-9c7d-11e6-8139-7d7ec6854f3a.png)

I hope everyone likes the idea. ;-)

Bye bye!

**Comment by viliusle** [comment]
Hello,
I don't understand what you mean. What is "view from afar" ?

**Comment by luihumberto** [comment]
"View from afar" is the [image](https://github.com/viliusle/miniPaint/issues/36#issue-185788900) I posted above, but in the program, okay?

**Comment by viliusle** [comment]
Thumbnail should always show all image, so use can knows which part is visible, so he can navigate easily.
