### ISSUE TITLE
Exe for local use?

### ISSUE THREAD

**Issue by gitihobo** [viliusle/miniPaint#381]
I dont have internet all the time, anyway I can use this locally?

**Comment by viliusle** [comment]
1. Download latest stable release from https://github.com/viliusle/miniPaint/releases
2. extract files from archive
3. open index.html (or create shortcut to Desktop and open it from there). At this step internet is not needed, unless you will try to use feature "Search images".

**Comment by gitihobo** [comment]
Awesome thank you very much, is there a way to auto update source code?

**Comment by viliusle** [comment]
No, but when you have internet, you can just use https://viliusle.github.io/miniPaint/
