### ISSUE TITLE
Customize language

### ISSUE THREAD

**Issue by matthieubrandt** [viliusle/miniPaint#385]
Hello there,

I have added NL.json. 

How can i make this language shown as main language.

Thanks!

**Comment by matthieubrandt** [comment]
[nl.json](https://github.com/viliusle/miniPaint/files/13353909/nl.json)

**Comment by phpony** [comment]
Put "nl" [here](https://github.com/viliusle/miniPaint/blob/d36fbadd86e49fbc62152e6f5c718b917f6769fe/src/js/config.js#L7) instead of "en".

**Comment by viliusle** [comment]
I also included Dutch as additional language & added your translations.

**Comment by matthieubrandt** [comment]
Thank you brother!
You are a great man!
