### ISSUE TITLE
License version?

### ISSUE THREAD

**Issue by RobAley** [viliusle/miniPaint#39]
The readme says the license is GPL, which is great. However it doesn't state which version (1,2 or 3), different versions have different requirements/restrictions, and doesn't include copyright statements etc. 

To properly protect the project, it may be worth following the guidelines here :
[https://www.gnu.org/licenses/gpl-howto.html](https://www.gnu.org/licenses/gpl-howto.html)
which are a quick way of making sure you have the right "legalese" in place.

Also, the reason that I created this issue was because we can't use or contribute to software where the legal/licensing situation isn't clear, and I want to use miniPaint as it looks like a great project.

**Comment by viliusle** [comment]
v3.

**Comment by RobAley** [comment]
That's great, thanks. I've made a pull request #40 to add the relevant attribution and license text. Now I can get on and see what I can contribute to the actual code itself :)
