### ISSUE TITLE
Change the Default Setting of transparent to On

### ISSUE THREAD

**Issue by takuyaW** [viliusle/miniPaint#394]
Hello,

First of all, I want to thank you for providing such an amazing project. I've been using miniPaint and have a question regarding the `settings` option for `transparent`.

Currently, the `transparent` option in `settings` is set to `off` by default. I was wondering if there's a possibility to change this default setting to `on`.

**Comment by viliusle** [comment]
You can change it on [config file](https://github.com/viliusle/miniPaint/blob/master/src/js/config.js#L5), rebuild and you will have it. 
If you are talking about changing it for everybody on https://viliusle.github.io/miniPaint/ - this is interesting, but it requires more opinions, research.

**Comment by takuyaW** [comment]
I tried making the changes in the config file and ran npm run build, but unfortunately, I didn't see the expected change to a transparent state. It seems that just changing the config settings may not be enough.

**Comment by viliusle** [comment]
after change, use incognito window, because once you save settings, it is saved in cookies. Settings works only if user is new and does not have any settings saved yet.

**Comment by takuyaW** [comment]
I have confirmed that the issue persists even when using an incognito window. Upon reviewing the code again, I identified that the problem is due to the `load_default_values` method in the `base-gui.js` file, where the setting is being changed to `false`. I plan to resolve this issue by changing the relevant code part to `true`. Thank you.

https://github.com/viliusle/miniPaint/blob/df0f259172234d645abfff91872863b33ab52077/src/js/core/base-gui.js#L92-L103

**Comment by viliusle** [comment]
Oh, in that case it looks like bug, I would try to remove line 96 at all, since default value should be in config.php- it could solve your issue.

**Comment by takuyaW** [comment]
Thank you for your quick reply.
I think there is a similar problem with the LANG variable, just like when config.TRANSPARENCY doesn't load correctly the first time. In this scenario, I think config.LANG should be loaded if lang is null.

https://github.com/viliusle/miniPaint/blob/df0f259172234d645abfff91872863b33ab52077/src/js/core/base-gui.js#L287-L300
