### ISSUE TITLE
Text tool not producing visible text

### ISSUE THREAD

**Issue by duncanch89** [viliusle/miniPaint#412]
The text tool does not work on my self-hosted version of this, but it works fine on other peoples' versions I've seen.

I used the latest docker image install method, it's running in a Debian 12 linux container in Proxmox.

Nothing useful in the logs from what I can see.

"asdfasdfasdfasdfasdf" - this is the text that I typed into the text box in the below screenshot. I was able to copy from the text box in the app, but no matter what I can't get it to become visible.

![image](https://github.com/user-attachments/assets/ba31ee59-ff28-4d96-a93b-6cda5c32bf3d)

Here are the logs. As I said, nothing useful, I don't think.

`> miniPaint@4.14.2 server
> webpack serve --mode development --env development --open

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://172.17.0.3:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/usr/src/app' directory
<i> [webpack-dev-middleware] wait until bundle finished: /
<i> [webpack-dev-middleware] wait until bundle finished: /
asset bundle.js 2.59 MiB [emitted] (name: main) 1 related asset
runtime modules 26.5 KiB 13 modules
orphan modules 15.9 KiB [orphan] 10 modules
modules by path ./src/js/ 1.26 MiB 218 modules
modules by path ./node_modules/ 724 KiB 47 modules
modules by path ./src/css/*.css 148 KiB
  ./src/css/reset.css 1.38 KiB [built] [code generated]
  ./src/css/utility.css 1.38 KiB [built] [code generated]
  ./src/css/component.css 1.39 KiB [built] [code generated]
  ./src/css/layout.css 1.38 KiB [built] [code generated]
  ./src/css/menu.css 1.38 KiB [built] [code generated]
  + 9 modules
webpack 5.89.0 compiled successfully in 22808 ms`

**Comment by viliusle** [comment]
Can you do Menu > File > Open > open test template and add screenshot here?

**Comment by duncanch89** [comment]
Thanks for the reply! The below screenshot has like 4 or 5 text boxes in it, all using different fonts, none of them are visible.

I also tried running it in a VM as opposed to a Linux Container, same issue.

![image](https://github.com/user-attachments/assets/9f1b4e23-190c-4dec-9df5-1dc95f491c01)

**Comment by viliusle** [comment]
Very strange, it is hard to help. Even I am not a person who wrote text module, if other tools are working, text should work too.

Do you see "Hello World" here?
https://www.w3schools.com/graphics/tryit.asp?filename=trycanvas_filltext

**Comment by duncanch89** [comment]
Yes, I see Hello World there. I sent you an email, hope you got it. Thanks
for your help.

**Comment by viliusle** [comment]
I see errors on console:
![11](https://github.com/user-attachments/assets/c1febc35-5637-4bff-a596-07d0ff3b1906)

**Comment by duncanch89** [comment]
> I see errors on console: ![11](https://private-user-images.githubusercontent.com/3708786/369490588-c1febc35-5637-4bff-a596-07d0ff3b1906.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDg1OTksIm5iZiI6MTcyNzAwODI5OSwicGF0aCI6Ii8zNzA4Nzg2LzM2OTQ5MDU4OC1jMWZlYmMzNS01NjM3LTRiZmYtYTU5Ni0wN2QwZmYzYjE5MDYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTIzMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTMwYTBlMzQxOTZkYTlhYjY0NzM4M2RkZmVkZTVmMTY5NThlYThmODJmNzhiNjJlYzRkZjU2MWM2MzQxZWQwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XwrybflQ6vDCquPGlA1XUijltU03qZ_dT9uNnGcX_do)

Any ideas? Does it seem like a permissions issue or something?

**Comment by duncanch89** [comment]
> I see errors on console: ![11](https://private-user-images.githubusercontent.com/3708786/369490588-c1febc35-5637-4bff-a596-07d0ff3b1906.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTEzODYsIm5iZiI6MTcyNzAxMTA4NiwicGF0aCI6Ii8zNzA4Nzg2LzM2OTQ5MDU4OC1jMWZlYmMzNS01NjM3LTRiZmYtYTU5Ni0wN2QwZmYzYjE5MDYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTMxODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFjZTRhMTc2MTljMmM2NGY0NWZlNTIxZDY1NzEzYjY3ZDQwZWM1ZmVlNTVkZGFiMDE3OTQ2MDA4YzQzOTNhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GLbDF5PQoPnXD8LgbqMjx9VL_ASnSQOgH_hH8XZaXsY)

I tried installing via the same method on an Amazon Lightsail instance and having the same issue. Could it be a Debian issue? I'm going to try in an Ubuntu LXC

**Comment by viliusle** [comment]
Looks like some conflict. Can you try with it out https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015 script? I see it in source code.

**Comment by duncanch89** [comment]
> Looks like some conflict. Can you try without https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015 script? I see it in source code.

I don't know how to do that, but I'll see if I can figure it out. Sorry, I'm used to Docker Compose, this project is the first time I've manually created a Dockerfile to build/run a container.

**Comment by duncanch89** [comment]
The text tool works fine when I use the npm install method, which I could never get to work in debian. Now that I've switched to Ubuntu, I was able to install using that method.

**Comment by duncanch89** [comment]
Okay, so I figured something out.

In order to make the app usable over a reverse proxy, I've been adding these two lines to webpack.config.js under "devServer:"

```
compress: true,
allowedHosts: 'all',
```
That section now looks like this:

```
        devServer: {
                // host: '0.0.0.0',
                //contentBase: "./",
                compress: true,
                allowedHosts: 'all',
                static: {
                        directory: path.resolve(__dirname, "./"),
                },
        }
```
If I don't add those lines, loading the webpage over reverse proxy results in a mostly blank page that only contains the text: "Invalid Host header".

But adding those lines is what breaks the text tool.

Here's my setup:

I am running minipaint on my local machine.
I am running Nginx on an AWS lightsail server.
I'm exposing my local IP addresses to that AWS server via tailscale.

Nothing changed when trying to run miniPaint on the AWS Lightsail system (rather than through the tailscale VPN).

**Comment by viliusle** [comment]
So problem solved?

**Comment by duncanch89** [comment]
> So problem solved?

I mean I guess so? The tool isn't any use to me if I can't use it over a reverse proxy, but that isn't your problem.

If you know how to get it working over a reverse proxy and maintain all functionality let me know, otherwise I'll look into what my alternatives are.

Thanks for your help!

**Comment by Giwayume** [comment]
@duncanch89 

> In order to make the app usable over a reverse proxy, I've been adding these two lines to webpack.config.js under "devServer:"

I'm late to this discussion, but unless you are developing locally on your machine, you shouldn't be relying on Webpack's development server. For a permanent install, create a build.

```
npm run build
```

Use nginx to serve the files generated in the "dist" folder directly.

```
server {
    listen 80;
    server_name localhost;

    root /path/to/dist;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
```
