### ISSUE TITLE
Cannot scroll an use all features of Effect menu item in small screen

### ISSUE THREAD

**Issue by tailetan** [viliusle/miniPaint#415]
Currently, we cannot scroll an use all features of Effect menu item in small screen. Please refer to the below attachment:

![2024-11-27_13h40_12](https://github.com/user-attachments/assets/aa25fa59-d230-4973-abc9-0bb297710eeb)

Could you please set the height of this menu dropdown to about 50%? @viliusle

**Comment by viliusle** [comment]
You can scroll, or drag to see rest menu items. I see scroll bar even on your screenshot. 
If you can do it, what is your browser, OS, device?

I just tested on multiple devices on both emulator and real android phone.

**Comment by tailetan** [comment]
I fixed it in the sketch plugin. Thank you for having a look on this.
