### ISSUE TITLE
uncredited copy of code on github

### ISSUE THREAD

**Issue by scruffynerf** [viliusle/miniPaint#417]
someone decided to just make a copy and slap his name on this as if he wrote it.

https://github.com/xylium117/PocketPainter

I didn't find your project until I saw a Chrome Extension
https://chromewebstore.google.com/detail/paintpro-free-professiona/edilbbjmcenabeecljloiiddlikhmpji
and said it's the same GUI, WTF?
(and at least that had a link to your code repo)

Is the chrome extension legit? or some other guy just packaging it?

**Comment by viliusle** [comment]
MIT license allows that. It is ok. 

p.s. I don't know these persons, there are no connections with me.
