### ISSUE TITLE
add ability to insert icons from a user gallery

### ISSUE THREAD

**Issue by synapse25** [viliusle/miniPaint#42]
I think this would be a fantastic feature, extremely usefl, please let me know if this is something you are willing to implement or if I should fork. Thanks.

**Comment by viliusle** [comment]
insert icons where? Do you mean using custom user icons in left sidebar tools area? If yes, i don't see reason for that. If you have better icons, share it and i will replace existing ones with better version.

**Comment by viliusle** [comment]
status update: i will try to implement this one day. Could be not easy because of CORS and no server-side part.

**Comment by viliusle** [comment]
Status update: image gallery added.
