### ISSUE TITLE
support for TIFF

### ISSUE THREAD

**Issue by zoro16** [viliusle/miniPaint#45]
Hi, thanks for the great work. 

I wanted to add support for TIFF and I thought it would nice if i get some directions.
the main issue for me now is to open the .tiff image.

Thanks

**Comment by viliusle** [comment]
TIFF is not supported by most browsers, (except safari?). You can try to pen tiff file with browser, and it will not open it. So TIFF usage in miniPaint is complicated, unless you use special libraries.
