### ISSUE TITLE
user access control, next/owncloud

### ISSUE THREAD

**Issue by andrkac** [viliusle/miniPaint#46]
Found that software right now and it looks great. I've installed a copy on my own server, but I see the disadvantage - there is no user access control. Anyone may use it on my server.
Do you have any kind of user access control in your roadmap? I think good idea is to integrate miniPaint with nextcloud (owncloud)

Using webdav filesystems should be also implemented if you want to consider using nextcloud/owncloud

**Comment by viliusle** [comment]
Yes, everybody can use, it. It is free app for everybody. So answer id no.

**Comment by andrkac** [comment]
That really great, that this is free app (and it's very fine and promising at all). I appreciate that. But in current state I think this is more like demo. I'm trying to realize a situation, where someone want to install and use it and I cannot. Access control does not exclude openness. And vice versa.
But, of course, it's your will and your decision. Ill be follow the app.
