### ISSUE TITLE
draw 5 rectangle on one layer,how to selected on rect and resize?

### ISSUE THREAD

**Issue by w8w8w8** [viliusle/miniPaint#47]
and, open one image, how to resize this image?
please help me

**Comment by w8w8w8** [comment]
i want to set the property of rectangle(line,text,image) .for example, color,size,and so on
but i do not know how to do!

**Comment by viliusle** [comment]
1. use different layers for each rectangle, so you can select layer and change its position. Now you can not select added objects. 
2. to resize image, use menu > image or layer > resize, or press R.
3. You can change color on left sidebar, but before you draw them.

**Comment by w8w8w8** [comment]
i see,thank you!
