### ISSUE TITLE
How to actually crop?

### ISSUE THREAD

**Issue by siyahmadde** [viliusle/miniPaint#48]
Hi,

Can you please suggest a proper way to crop the image?

I select the area with the crop tool and create a new layer from the selected area and delete the main layer but in that case canvas does not resize automaticaly as it can be seen.

Thanks!

![image](https://cloud.githubusercontent.com/assets/18377668/24488798/1543d994-1522-11e7-9dad-a3002395409c.png)

**Comment by viliusle** [comment]
Click crop tool, select area to crop and click on selected are to do actual crop.

p.s. you can use shortcut "T" to trim image , so extra padding will be removed.

**Comment by siyahmadde** [comment]
Thanks!
