### ISSUE TITLE
Features and questions

### ISSUE THREAD

**Issue by berserk82** [viliusle/miniPaint#49]
Hello there.
My name is Ivano Arrighetta and I'm Italian.
I have 2 questions about MiniPaint:
1) How is the browser support?
2) Can it be used locally (without a server) and/or on a web server (without frameworks like node or something else)?

And some feature requests:
brush - with blending modes
lines and splines - with style (dashed, dotted, thickness, cap, join, etc)
cage transform
translate/rotate/scale
offset (wrap the image horizontally and/or vertically)
layers with blending modes
selection - lasso, by color - with invert, add and substract
alpha masking
alpha blending
text - following a path or filling a shape
flood fill - with gradient or texture
stroke - with style (as above)

Thanks in advance for any help.

Bye, Ivano.

**Comment by viliusle** [comment]
Hello,
1. It works on chrome, firefox, edge, safari, opera and IE11.
2. Even now it works without server, you can download files and run it on your local pc with out any install.

Brush - YES. Blending modes - not yet. But there is layers and you can use blending modes on layers.
Lines - YES, just missing few features.
cage transform - NO
rotate, scale - YES
translate - MAYBE, (only with mouse)
layers  with blending modes - YES.
selection - lasso - NO
selection by color - NO, but there is color replace
alpha masking - NO, (there is layers blending)
alpha blending - not sure about meaning, but there is full transparency and layers support.
text - following a path or filling a shape - NO
flood fill - with gradient or texture - NO, just simple flood fill, but you can get same effect with multiple tools like magic and tool, transparency, multiple layers.
stroke - with style (as above) - NO

**Comment by berserk82** [comment]
Would you mind implementing missing features (except cage transform)?

**Comment by viliusle** [comment]
I will implement some of them.
Some are possible using multiple tools on multiple layers, so its not a problem.

What is left -  is complicated (or rarely used and wont be implemented, like:
selection - lasso
text - following a path or filling a shape 
... with gradient or texture...

p.s. This is not replacement for Photoshop or Gimp.

**Comment by berserk82** [comment]
Thanks a lot, I greatly appreciate this.
Let me know whatever you need, I'll do mi best.
