### ISSUE TITLE
General features

### ISSUE THREAD

**Issue by berserk82** [viliusle/miniPaint#50]
Hello again. I wonder if this project does support the following features:
undo
redo
cut
copy
paste
save/export
new
close
open
zoom

Thanks in advance for either.

Bye, Ivano.

**Comment by jcfrog** [comment]
did you try it? :)

**Comment by berserk82** [comment]
Yes, but I don't remember and I can't access my computer for some time.

**Comment by viliusle** [comment]
Check readme.md for feature list, you will find all these feature you listed. 

Basically all basic features are (must be) supported.
