### ISSUE TITLE
Issue with the Pick color tool

### ISSUE THREAD

**Issue by Toad06** [viliusle/miniPaint#52]
Hello,

If you use the "Pick color" tool in a place where there is actually no color (transparent background), this will crash the app. After that, for example, the "Brush" tool will draw nothing and the "Fill" tool will crash the browser (infinite loop?).

Tested on the online demo with Firefox and Chrome.

**Comment by viliusle** [comment]
Color pick picks transparent color, so brush paints transparent (invisible) color too :D But it is very confusing and will b fixes soon. 
p.s. using fill tool after that actually does infinitive loop.

Thank you.

**Comment by Toad06** [comment]
Well, this makes sense. :)

I should have written that nothing was drawn even after selecting a color in the table on the left. But I was wrong anyway because I haven't noticed the alpha value remained to 0. So actually the title of this report should be "Issue with the Fill tool when alpha is set to 0". But you have already fixed all this stuff. :)
