### ISSUE TITLE
Minor issue with number inputs

### ISSUE THREAD

**Issue by Toad06** [viliusle/miniPaint#53]
Hello,

Using the arrows of a number input will actually not change the relevant value. This seems to happen every time the "plus" and "minus" buttons are provided. For example, in the "Brush" tool, change the size with the arrows instead of the +/- buttons and notice the size actually remains to 10.

**Comment by viliusle** [comment]
I can not reproduce it. Which browser, which scenario? Using both buttons or keyboards works, but i found few related anomalies in code, maybe it will help.

**Comment by Toad06** [comment]
Both Firefox and Chrome. My explanations were not really clear, I have attached an image so it will be easier to see what I was talking about.

Adding this attribute to the input seems to fix it (only tested on Firefox):
oninput="GUI.update_attribute(this);"

![brush](https://user-images.githubusercontent.com/14274782/27075981-2215bb5c-502c-11e7-82a7-0f57d0bb40de.png)

**Comment by viliusle** [comment]
another, final fix should be on 3.3.4 version.
