### ISSUE TITLE
Tried the demo another time, can't find layer blend modes

### ISSUE THREAD

**Issue by Berserk82** [viliusle/miniPaint#58]
As in subject, I had a deeper look at the demo, but I can't find layer blend modes.
I just can see transparency.
Is that the only blend mode available?

Thanks in advance.

**Comment by viliusle** [comment]
Menu > layer > merge down > select composition or blend mode and activate it in section "Mode". 
You should see instant changes on preview.

Basically you can use composition types, if you want to use Blend, you have to activate it using checkbox below "Mode > Blend".

Sorry for not perfect UX. It is possible that i will improve it in future.

>I just can see transparency.
maybe you have both empty layers?

**Comment by Berserk82** [comment]
No, I tried with 2 gradients. (One black and white, one coloured)
So is there no way to change layer blend mode after merging, right?

**Comment by viliusle** [comment]
right. It works only during layer merge.

**Comment by viliusle** [comment]
Status update: blend modes are supported now.
