### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Toad06** [viliusle/miniPaint#60]
Hello,

I have checked and improved the French translation and added some missing fields. However, texts in input fields, errors, or alt attributes are not translated for some reasons.

There are also two little mistakes:
- Gradient tool => "Text" is displayed in the box
- Effects => Vibrance => "Vignette" is displayed in the box

[fr-tr.zip](https://github.com/viliusle/miniPaint/files/1130614/fr-tr.zip)

**Comment by viliusle** [comment]
i will add this to next minor version. Thank you.
