### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by Toad06** [viliusle/miniPaint#61]
Hello,

Some minor issues with layers, tested on Firefox.
Steps to reproduce...

BUG 1
- Draw something.
- Click on the cross to delete the layer.
- Notice the layer is now blank on the main window but not on the preview window on the right (you will need to click on the cross one more time). This only happens if there is a single layer.

BUG 2
- Draw something.
- Choose the "Select area tool" and use it somewhere.
- "Copy selection" then "Paste selection" in the miniPaint menu.
- Notice you will have now two "Layer #1". If you play with the "Hide" button, you will see that both hide it on the main window (but not on the preview window). This bug happens even if you have many layers.

BUG 3
- Draw something.
- Choose the "Select area tool" and use it somewhere.
- Now press CTRL + Z to undo. This will remove what you have drawn before, but for some reason the layer is also deleted, meaning that any attempt to draw something will result in a JavaScript error: "TypeError: LAYER.layers[LAYER.layer_active] is undefined". It does not seem to be a permanent issue and creating a new layer makes the app work again without the need to restart it.

**Comment by viliusle** [comment]
BUG 1 - minor
BUG 2 and 3 - important.

I will try to fix it soon. Thank you.

p.s. github does not alert me if edit was made, so please use reply for major content edits. (or i will not be notified....)
