### ISSUE TITLE
Problem with getting image into image editor and scaling

### ISSUE THREAD

**Issue by NJseo** [viliusle/miniPaint#64]
Hi, 
I have tried your recommendations for getting an img object into the editing window listed on https://github.com/viliusle/miniPaint/issues/44.

Using the last update change I get a cutoff on the image as it doesn't scale to the image. Any zooming after shows a cutoff of image. Adjustments to the css after the fact just shows a cutoff image. 
<script>
function open_image(image_id){
	var img = document.getElementById(image_id);
	//set name
	var name = img.src.replace(/^.*[\\\/]/, '');
	LAYER.layer_add(name);
	LAYER.layer_remove(1);
	//draw canvas
	canvas_active().drawImage(img, 0, 0);
}
</script>

So, then I tried working with the first suggestion, and that failed to add the layer. I noticed too in file.js that instead of calling the object as a variable, the code reverts to using a getElementByID which I think should be called using the object variable.

Anyhow, your help in completing this task and overcoming this error would be greatly appreciated.

**Comment by viliusle** [comment]
try this custom function and let me know if it works fine for you.

```
<img alt="" id="my_image" src="********" onclick="open_image_custom('my_image');"  />

function open_image_custom(image_id) {
	var img = document.getElementById(image_id);

	//set name
	var name = img.src.replace(/^.*[\\\/]/, '');
	LAYER.layer_add(name);
	LAYER.layer_remove(1);
	
	if (img.width > WIDTH || img.height > HEIGHT) {
		if (img.width > WIDTH)
			WIDTH = img.width;
		if (img.height > HEIGHT)
			HEIGHT = img.height;
		LAYER.set_canvas_size();
	}

	//draw canvas
	canvas_active().drawImage(img, 0, 0);
	IMAGE.trim();
	GUI.zoom_auto(true);
}
```

**Comment by viliusle** [comment]
if you want to use onclick="open_image_custom(this);" change function param to (img) and remov code with getElementById()

**Comment by NJseo** [comment]
Thank you so much. I will apply suggestions and test.

**Comment by NJseo** [comment]
Solved
