### ISSUE TITLE
Clone tool doesnt work as expected

### ISSUE THREAD

**Issue by NJseo** [viliusle/miniPaint#67]
Needs update

**Comment by viliusle** [comment]
what is wrong with it? it works for me.

**Comment by NJseo** [comment]
You can select an area, then redraw of another, but the originally starting point is not followed to the tip of airbrush. So if I have a circle on the left hand of the screen and I want to redraw it on the right, the result does not reproduce the circle on the left after completion. What it will produce in the same starting spot repeated over and over again.

In tradition of clone, it should follow and move from the starting point using xy coords in relation to the copyTo point, thereby duplicated the full original image after the xy paths are covered. From my test, it did not work in that manner.

**Comment by viliusle** [comment]
i will update tool, but it will take some time.

**Comment by NJseo** [comment]
Understood

**Comment by viliusle** [comment]
Clone tool reworked. Also draw from previous layer supported. Please look  and let me know if any issues left. And thank you very much for report - clone tool is much more better now.
