### ISSUE TITLE
How to specify default image URL - Save and Opening other image issues

### ISSUE THREAD

**Issue by jmguiry2014** [viliusle/miniPaint#69]
I used the fix you provided in issue #44 to pass in an image to be opened automatically.
```
<img alt="" id="my_image" src="img/colorwheel.png" alt="" onclick="FILE.open_image('my_image')"  />
<script>
function open_image(image_id){
	var img = document.getElementById(image_id);
	//set name
	var name = img.src.replace(/^.*[\\\/]/, '');
	LAYER.layer_add(name);
	LAYER.layer_remove(1);
	//draw canvas
	canvas_active().drawImage(img, 0, 0);
}
</script>
```

However, now I am experiencing issues when attempting to save the image or open another image and then saving. Right after loading the page with the preselected image, if I attempt to save without doing any edits the screen simply reloads quickly but does not save. If I do an edit or open another image it will save, but will then reload the screen with the original image with no edits and/or without the other image opened.

What I am attempting to do is pass in an image (successful with your fix), and then edit the image (possibly with other local images that I open). After completing the edits I need to be able to gather the information on the image to send it back to the server to be stored.

**Comment by viliusle** [comment]
check this example:

```
<img style="position:fixed;bottom:0;right:0;" alt="" id="my_image" src="img/colorwheel.png" onclick="open_image('my_image')"  />
<button style="position:fixed;bottom:0;right:0;" onclick="my_save()">Save</button>
<script>
function open_image(image_id){
	var img = document.getElementById(image_id);
	//set name
	var name = img.src.replace(/^.*[\\\/]/, '');
	LAYER.layer_add(name);
	LAYER.layer_remove(1);
	//draw canvas
	canvas_active().drawImage(img, 0, 0);
}

function my_save(){
	var tempCanvas = document.createElement("canvas");
	var tempCtx = tempCanvas.getContext("2d");
	tempCanvas.width = WIDTH;
	tempCanvas.height = HEIGHT;
	LAYER.export_layers_to_canvas(tempCtx, 'PNG', false);
	tempCanvas.toBlob(function(blob) {
		//image data here
		//console.log(blob);  //uncomment to debug
		
		//post data to your server....
		alert('Fake action to send data ('+blob.size+' bytes) to server...');   //remove it !!!
		
		var xhr = new XMLHttpRequest();
		xhr.open("POST", 'http://127.0.0.1/', true); //change  url
		xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");
		xhr.send(blob);
	});
}
```

**Comment by jmguiry2014** [comment]
This works great! Thank you so much!!

**Comment by bradsapp** [comment]
This worked for me as well except I can't get the canvas to update the width and height. As a result when I open an image the default canvas size is 800x600 so the image is cut off. Any suggestions on how to resolve this?

**Comment by jmguiry2014** [comment]
@bradsapp I don't know if this is the fix you were looking for or if it's the proper way that viliusle recommends but I added GUI.zoom_auto(); like this:

`<img style="position:fixed;bottom:0;right:0;" alt="" id="my_image" src="img/colorwheel.png" onclick="FILE.open_image('my_image'); GUI.zoom_auto();"  />`

**Comment by bradsapp** [comment]
Thanks for the quick reply. But that doesn't work. It just zooms out. Still cuts off the image. I'm using an image 1080x1080.

**Comment by viliusle** [comment]
working example:
<img style="position:fixed;right:0;bottom:0;" alt="" id="my_image" src="img/colorwheel.png" onclick="FILE.open_image('my_image');"  />

**Comment by bradsapp** [comment]
@viliusle Thanks for the reply. Yes that does work, but it doesn't work for images that are larger than the canvas. My image loads into the editor, but when I try to expand the editor my image has been cut off. The canvas starts at 800x600, when I click my image in the bottom right it loads into the editor, but when I try to expand the editor my image remains at 800x600 so I'm missing part of my image. I need the canvas and editor to auto expand the dimensions of my image.

![screen shot 2017-10-27 at 08 07 14](https://user-images.githubusercontent.com/1902512/32105386-e3459852-baed-11e7-8477-ed0f6bc616b5.png)

**Comment by viliusle** [comment]
what version you are using? Because this bug existed in past and it was fixed on 3.4+ i believe.

p.s. i understand you issue, in lastest version it was already fixed.

basically function should look like:

```
this.open_image = function(image_id) {
		var img = document.getElementById(image_id);
		
		//set name
		var name = img.src.replace(/^.*[\\\/]/, '');
		LAYER.layer_add(name);
		LAYER.layer_remove(1);
		
		if (img.width > WIDTH || img.height > HEIGHT) {
			if (img.width > WIDTH)
				WIDTH = img.width;
			if (img.height > HEIGHT)
				HEIGHT = img.height;
			LAYER.set_canvas_size();
		}
		
		//draw canvas
		canvas_active().drawImage(img, 0, 0);
		IMAGE.trim();
		GUI.zoom_auto(true);
	};
```

**Comment by bradsapp** [comment]
Great that worked! Thanks for the help.  One last question, are we able to use this for files hosted on AWS? Or will we have to download the images to the server in order to let users modify them?

**Comment by viliusle** [comment]
it depends. If server provides correct CORS headers, you can load image from that external server. If not - only way is to use some server side proxy. For example: this is my test image on remote server that works: http://i.imgur.com/ATda8Ae.jpg

Is that AWS yours? if yes - configure CORS (i beleive it is posible), and you will be able to load images from AWS.
