### ISSUE TITLE
Cant Load Big Images error : NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by darkworks** [viliusle/miniPaint#71]
am using latest latest version of minipaint
am using latest version of firefox 
i tried to load image of dimension 14000 x 10000 and its displaying blank canvas , i check logs and it display error NS_ERROR_FAILURE at

```
NS_ERROR_FAILURE:     image.js:561
IMAGE_CLASS/this.trim_info        http://viliusle.github.io/miniPaint/js/image.js:561:13
LAYER_CLASS/this.layer_add/img.onload           http://viliusle.github.io/miniPaint/js/layers.js:137:22
```

so any idea how to over come this problem so that we can load high resolution image like up to 20k dimensions

**Comment by viliusle** [comment]
Very interesting issue report .

Lets use chrome, miniPaint and  this image for testing: 17 242 x 8 590 = 150 megapixels.
https://c2.staticflickr.com/2/1538/25626842713_619a50cc0c_o.jpg (dont click on mobile !)

Chrome tab uses almost 4GB or RAM and crashes, because it exceeds max memory i guess. I am using several canvas elements to render image. So basically current version use lots of RAM and do not support big images.

p.s. ms Paint can not open such big images too :)

**Comment by viliusle** [comment]
Now good news.

Next version of miniPaint **will** support big images, its not finished yet, still missing few features.

just opened same image on new version, chrome used 336 MB or RAM and opens it without problems. Tried to save it using jpg with 1% quality - worked.

So please wait for next version.

![demo](https://user-images.githubusercontent.com/3708786/31683902-e1b8fd26-b386-11e7-805c-9798d63ee74c.jpg)

**Comment by jmguiry2014** [comment]
@viliusle, I'm curious but do we have an ETA for the new version?

**Comment by viliusle** [comment]
basically these features are missing: half of left side tools (including select), rotate, undo system, translations.

I can push current stable version to master branch with something like 85% functions in few days actually, so everybody can download it manually and preview it. **Or** in few months i believe everything or most of it should be finished and pushed live i believe. My current plan is to finish it, test everything and only then push to live.

**Comment by jmguiry2014** [comment]
@viliusle awesome to hear! I'm excited to see this release. You have done a great job with this editor.

**Comment by darkworks** [comment]
thanks for quick response :) , also please work on zoom feature too , i mostly worked with 600 DPI images which are above 7K recently i had 13K images to work with ya chrome opened and crashed while firefox just display blank canva ...  
so please also work on zoom feature , so that we can zoom in very low on image because currently zoom in on big images will also cause too memory usage and crash it , and that happen when we move layer too , i mean if you have try move big layer then after few shifts it will crash ... its occur because we dump a lot of data with getimage data and browsers do not release memory on time or can say quickly , also there is no way in browsers to trigger there GC they run it whenever there is no references left and execution , as i mentioned i worked with high DPI so i had a lot of memory issues so i handled them by using threads , which allowed me not to wait for browser GC , i do mostly heavy work inside thread and when it die memory is released because its separate sandbox , so i would suggest if you want you can use threads in it , its very effective , when i had to process big images i split there data among multiple threads sometime i had to create 40+ threads when am on 600 dpi , and it end merge their results and memory free :)  try it : https://github.com/austinksmith/Hamsters.js
use it in persistence mode off  , for less memory  , i had few issue with persistence mode ON , i reported it and its developer fix a bit

**Comment by viliusle** [comment]
**Status update**: major version just released, but super big images does not work on chrome (dont know why yet, will work on it). IT works better of Firefox, still issues with saving.

**Comment by darkworks** [comment]
nice , its good to see major update , i noticed its  using webpacks , 
so any idea how can we setup development environment of it , i have not worked with webpacks , i replaced 
`<script src="dist/bundle.js"></script>`
with 
` <script src="src/js/main.js"></script>`

but giving import error in console , so how can we setup it development mode so that custom change could reflect instantly without building it for every change 
thanks

**Comment by darkworks** [comment]
nice , its good to see major update , i noticed its using webpacks ,
so any idea how can we setup development environment of it , i have not worked with webpacks , i replaced
<script src="dist/bundle.js"></script>
with
<script type="module" src="src/js/main.js"></script>

but it give error

Uncaught TypeError: Failed to resolve module specifier 'alertifyjs/build/css/alertify.min.css'
so how can we setup it development mode so that custom change could reflect instantly without building it for every change
thanks

**Comment by viliusle** [comment]
check "Build instructions" section on readme.md in homepage.

**Comment by darkworks** [comment]
ya i run npm install and it created folder node_modules  where it stored all dependencies  but am still getting 
alertifyjs/build/css/alertify.min.css

so can you guide me where to move the dependencies
thanks

**Comment by viliusle** [comment]
strange, try including modules with full path like:
import alertify from 'alertifyjs/build/alertify.min.js';
=>
import alertify from './../../../node_modules/alertifyjs/build/alertify.min.js';

i will test clean build later today.

**Comment by darkworks** [comment]
thanks for updating it 
now i get these error ,

```
reset.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
print.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
layout.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
alertify.min.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
menu.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
popup.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by darkworks** [comment]
also on live demo site , i tried to use fill tool on circle and get alert 

> Layer must be image, convert it to raster to apply this tool

so how to convert it to image , ?
thanks

**Comment by viliusle** [comment]
Layer > convert to raster. 
Basically you can not apply some features on vector objects, only edit vector.

**Comment by darkworks** [comment]
ok thanks , Also i updated my locally copy according to your recent commits in which you update paths  of dependencies , so now am getting these errors 

```
reset.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
print.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
layout.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
alertify.min.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
menu.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
popup.css:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
```

my main js is set like 
```
	<!-- <script src="dist/bundle.js"></script>  -->
	 <script type="module" src="src/js/main.js"></script>
```
i have added type module because chrome latest version still not support import feature i think

**Comment by viliusle** [comment]
Dont edit main, and dont touch this line: `<script src="dist/bundle.js"></script>`.  You have to follow Build instructions on readme.md. Use one of these ways to develop: 

1. "webpack-dev-server" - after that access app here: http://localhost:8080/. In order to see changes after server shutdown, run "webpack" once.
2.  "webpack --watch" and just load index.html

**Comment by darkworks** [comment]
ok great :) ya i can load index.html when i visit http://localhost:8080/   ... so how can i load index.php , i mean i will have to add some php code to index, so i will have to rename it to index.php from index.html
thanks

**Comment by viliusle** [comment]
rename it to index.php and use some WAMP server then, not webpackd-dev-server. Also you will need to run webpack using "webpack --watch" for dev.

**Comment by viliusle** [comment]
Also better don't use 1 issue page for all questions. Create another issue if you have other questions.

**Comment by darkworks** [comment]
ok ya got it , because earlier webpack dev server trigger download of index.php
