### ISSUE TITLE
Possible to hook into the Save/Open function?

### ISSUE THREAD

**Issue by Sebjugate** [viliusle/miniPaint#77]
I apologize is this is documented somewhere, but I couldn't find it. I would like to use miniPaint as an editor for images from an internal website. This would involve:

- Passing initial image data into miniPaint window on load (via window.postMessage(), or query parameter)
- Hooking into the save function to return PNG image data back to the calling page via window.postMessage() rather than bringing up the save dialog.

Is this possible?

**Comment by Sebjugate** [comment]
I somehow missed the examples folder, which basically has this. I'll check that out.

**Comment by theevilqueen77** [comment]
I'm attempting this in the new version as well, but I'm not using the editor via iframe which is the example given in the Wiki. I attempted to replace the id for var Layers with the canvas id (canvas_minipaint) but that is not working. Below is the format I used for the canvas (the one @viliusle provided):

```
<div class="main_wrapper" id="main_wrapper">
    <div class="canvas_wrapper" id="canvas_wrapper">
           <div id="mouse"></div>
	    <div class="transparent-grid" id="canvas_minipaint_background"></div>
	    <canvas id="canvas_minipaint">
		    <div class="trn error">
			    Your browser does not support canvas or JavaScript is not enabled.
		    </div>
	    </canvas>
    </div>
</div>
```

**Comment by viliusle** [comment]
Please explain problem and what you are doing, because i dont understand you.

**Comment by viliusle** [comment]
if you are not using iframe, you can access layers class like this: `window.Layers` , of course after onload event.

**Comment by theevilqueen77** [comment]
In the example in open-edit-save.html the function open_image references the id in the iframe

```
function open_image(image){
	if(typeof image == 'string'){
		image = document.getElementById(image);
	}
	var Layers = document.getElementById('myFrame').contentWindow.Layers;
	var name = image.src.replace(/^.*[\\\/]/, '');
	var new_layer = {
		name: name,
		type: 'image',
		data: image,
		width: image.naturalWidth || image.width,
		height: image.naturalHeight || image.height,
		width_original: image.naturalWidth || image.width,
		height_original: image.naturalHeight || image.height,
	};
	Layers.insert(new_layer);
}
```

I tried to change the Layer to reference the canvas's id instead to open the image on page load, but it isn't working.

**Comment by theevilqueen77** [comment]
Since I'm not using iframe would the open_image function work something like this then?

```
            function open_image(image) {                
                if (typeof image == 'string') {
                    image = document.getElementById(image);
                }
                var name = image.src.replace(/^.*[\\\/]/, '');
                var new_layer = {
                    name: name,
                    type: 'image',
                    data: image,
                    width: image.naturalWidth || image.width,
                    height: image.naturalHeight || image.height,
                    width_original: image.naturalWidth || image.width,
                    height_original: image.naturalHeight || image.height,
                };
                window.Layers.insert(new_layer);                
            }
```
I've tested all of the steps in between and I am getting the expected results, but the editor won't open the image on load even though I'm using window.Layers and I am not using iframe.

**Comment by theevilqueen77** [comment]
Sorry for overloading you with comments. I noticed in the wiki examples this comment.

> Note: You can access layers class globally: window.Layers or document.getElementById('miniPaint').contentWindow.Layers if outside of iframe.

I think you meant inside of the iframe and not out?

Also, going back to the issue I am experiencing with getting the editor to open an image on load. This is the code I am using in the open_image function:

```
           function open_image(image) {                
                if (typeof image == 'string') {
                    image = document.getElementById(image);
                }
                var name = image.src.replace(/^.*[\\\/]/, '');
                var new_layer = {
                    name: name,
                    type: 'image',
                    data: image,
                    width: image.naturalWidth || image.width,
                    height: image.naturalHeight || image.height,
                    width_original: image.naturalWidth || image.width,
                    height_original: image.naturalHeight || image.height,
                };
                window.Layers.insert(new_layer);
            }
```
I have checked and new_layer has all of the correct information from the image that I am passing through to load but it isn't being inserted.

**Comment by theevilqueen77** [comment]
Sorry to bug you, again, but I wanted to say that the above code is working correctly but only if I actually click on the image myself. In the previous version of the library I was able to hide the image and get the image to load with clicking the image with jquery which I can no longer do which is why I thought it wasn't working. Do you have any ideas why that would be?

**Comment by viliusle** [comment]
>I think you meant inside of the iframe and not out?

If your code in same iframe with miniPaint, you can access it using global variable `window.Layers` or just simple include that and create new class (its singleton). But if miniPaint is in iframe, and your code - not, in order to access that global variable, you need first to get iframe instance.

**Comment by viliusle** [comment]
Adding this code works fine in open-edit-save.html. No need to use jQuery and force click.
```
window.onload = function (e) {
	open_image(document.getElementById('testImage'));
};
```
p.s. in general, setTimeout is evil.

**Comment by Schavez70** [comment]
I am very new to this in the example above the document.getElementById('testImage') is that a image reference  as in a file location string or is that a stream or Byte array?  I am trying to let users select a thumbnail from outside an iframe and make and Ajax call to get the image from the server to load into the Canvas.  LOL... is that even possible?
