### ISSUE TITLE
Building MiniPaint Issues

### ISSUE THREAD

**Issue by jmguiry2014** [viliusle/miniPaint#78]
I may have missed more detailed instructions then this:

git clone https://github.com/viliusle/miniPaint.git
cd miniPaint
npm install
webpack-dev-server (using http://localhost:8080/ with live reload, require: npm install -g webpack-dev-server)
edit files...
webpack -p (build for production)

I'm having issues with webpack, and I'm also looking at the main.js which the webpack.config.js looks to to build and I noticed that the node_modules import wasn't a path in the downloaded copy of the library. 

Is this the correct guide to installing webpack? https://webpack.js.org/guides/installation/

**Comment by viliusle** [comment]
node_modules folder is generated after executing "npm install". It is included in library, just in compressed/config form in package.json file.

Yes, that guide link is correct. Basically all you need to to and i not written in my build instructions, also execute command "npm install --global webpack".

Let me know if you still have issues, or if something is not clear. i will improve documentation.

**Comment by viliusle** [comment]
Wiki was added: https://github.com/viliusle/miniPaint/wiki/Build-instructions
