### ISSUE TITLE
How to expose the build library to outside?

### ISSUE THREAD

**Issue by darkworks** [viliusle/miniPaint#79]
Am trying to expose the library to outside so that i can use classes functions and also can pass data to it from outside , so i wonder how to do it , as am not familiar with webpacks . i did bit search so according to : http://webpack.github.io/docs/configuration.html#output-library

i modified webpack.config.js file  and change the output block  to 
```
	output: {
		filename: 'dist/bundle.js', 
		libraryTarget: 'var',
		library: 'mplib'
	},
```

but still i cant access Base_layers_class member functions 
so can you add documentation to extend minipaint and to pass and use minipaint functionality from outside

**Comment by viliusle** [comment]
everything in webpack module is not exposed to global scope by default. But it can be done like: 
```
global test = 'value';
window.test = 'value'; 
```
Base_layers_class class is already registerd in global scope and you can access it like **window.Layers**.
Related example: https://github.com/viliusle/miniPaint/blob/master/examples/open-edit-save.html#L37
(Line 26 must be used in case app is in iframe)
 
If you are missing other classes, let me know.

p.s. better dont edit webpack.config or core files.

**Comment by viliusle** [comment]
I really need to add more documentation, and i will do it as first priority.

**Comment by darkworks** [comment]
ya documentation will be good 

i tried `window.Layers.get_dimensions()`
and get error
`Uncaught TypeError: Cannot read property 'get_dimensions' of undefined`

**Comment by viliusle** [comment]
window.Layers is not available if miniPaint is in iframe. 
`var Layers = document.getElementById('myFrame').contentWindow.Layers;`

**Comment by viliusle** [comment]
updated: wiki was added.

**Comment by darkworks** [comment]
ya i checked wiki , but its missing part of accessing classes from outside and passing data to it 
the iframe method u used in examples folder when i open page and click update it give error 

`Not allowed to load local resource: file:///C:/xampp/htdocs`

and when click save button it give error
`Cannot read property 'get_dimensions' of undefined`

i wish there was some direct way of accessing and passing data to classes :( this webpacks is strange , interactivity with code is bad .

**Comment by darkworks** [comment]
ok great :) .
