### ISSUE TITLE
Preview Canvas Resize

### ISSUE THREAD

**Issue by theevilqueen77** [viliusle/miniPaint#80]
In the previous version I had the PREVIEW_SIZE width and height be dynamic dependent upon the image loaded with the following code:

```
// preview mini window size on right sidebar
var a = document.getElementById('canvas_minipaint').naturalWidth;
var b = document.getElementById('canvas_minipaint').naturalHeight;
this.PREVIEW_SIZE = {w: a, h: b};
```

However, now if I add that into gui-preview.js it causes issues with the canvas_preview_wrapper (doesn't resize properly because the template is hard coded), the canvas_preview (doesn't reload the layers properly if edits are done to the image such as selection), and the canvas_minipaint if need_fit is set to true.

**Comment by viliusle** [comment]
i dont understand you, you should not change preview size, only zoom level. Preview is always same size. 

If after some action preview is not refreshed, you can do it manually but requesting rendering on next frame:
`config.need_render = true;`

**Comment by theevilqueen77** [comment]
In the previous version, I changed the preview size because depending on the image we were using it was skewed due to the fixed sizes which is why I added the code from above to the gui.js file. It didn't cause any issues and was wondering if you had any idea of why it would cause issues in this new library. Thanks for getting back to me.

**Comment by viliusle** [comment]
I am afraid it can not be fixed so easily, at least some extra work must be done (maybe). I will delay this probably, because its not high priority.

**Comment by theevilqueen77** [comment]
I have been able to implement this if you'd like for me to send it to you.

**Comment by viliusle** [comment]
Please do that if you have time. (https://github.com/viliusle/miniPaint/wiki/Contributing)
My current todo is big (no major issues, happy), i need to start working on them.

**Comment by viliusle** [comment]
Or just send updates, i will do testing.
