### ISSUE TITLE
Crop Feature Request

### ISSUE THREAD

**Issue by theevilqueen77** [viliusle/miniPaint#82]
Crop boundaries options such as being bound to ratios (1:1) or editable width/height specifications (300px/500px).

**Comment by viliusle** [comment]
I will add crop with 1:1 if CTRL is pressed, will be easy to implement. Custom size can be set on image > size. (but it will not drop unvisible data as crop does)

**Comment by theevilqueen77** [comment]
Thank you!

**Comment by theevilqueen77** [comment]
Would this include maintaining the ratio when resizing the control boundaries? Also, would it be possible to move the boundaries by clicking inside of it a dragging?

**Comment by theevilqueen77** [comment]
I have been able to do this (defining the ratio of the boundary area) if you would like for me to send this to you.

**Comment by viliusle** [comment]
Contributing is always welcome
