### ISSUE TITLE
IE Effects

### ISSUE THREAD

**Issue by banrionjackie** [viliusle/miniPaint#83]
I know you said that IE 11 support is basic, but I was wondering if the effects aren't supposed to work in IE 11 now. I checked your demo and things like Sepia, Grayscale, Gaussian blur, etc. aren't working but when I rolled back to your demo for the previous version those effects were functional.

**Comment by viliusle** [comment]
Some filters were changed from custom implementation to using standarts. Sadly IE11  does not support many standarts and even worst - it will NEVER be fixed.

But thank you for report, fallback to old code should be used and i will work on that.

**Comment by viliusle** [comment]
p.s. nobody should use IE11.

**Comment by theevilqueen77** [comment]
Thanks for that. I was just wondering because some of the effects *seemed* the same at first glance and I wasn't sure what was going on. I appreciate all of your hard work on your awesome product!

**Comment by theevilqueen77** [comment]
I definitely agree. I abhor IE with all of my being. Unfortunately, the majority of the people using the end product I'm helping with use IE

**Comment by viliusle** [comment]
Css effects (separate menu) are like 1000x faster and can be removed in layers list. Sadly no support on IE/Edge.
Other effects were not changed, just migrated.

**Comment by theevilqueen77** [comment]
Sepia, Grayscale, Gaussian blur, and a couple of others were added under CSS effects in the new version, but were functional in IE in the old version. Will those still fall back on old code eventually?

**Comment by viliusle** [comment]
that my plan, any effect, that was working and now not - should be added as fall back.

**Comment by theevilqueen77** [comment]
Okay, awesome. I got confused by your previous comment.

**Comment by viliusle** [comment]
Because Edge will soon use chronium engine (it will work as chrome) and and developing for IE only is difficult and and makes no sense 2019, IE effects will never be fixed.
