### ISSUE TITLE
Request: Method to drag crop area around before confirming crop

### ISSUE THREAD

**Issue by KyleABrown** [viliusle/miniPaint#85]
Hi, 
Love the work. Is there currently a way to drag the crop area around before confirming? I have skimmed the code and can't seem to find anything. If there isn't, can you point me to the appropriate place to implement such a method?

**Comment by viliusle** [comment]
/src/js/tools/selection.js (line 111) has it.
Should be added to /src/js/tools/crop.js, or even better, coreselection lib could get that feature at src/js/core/base-selection.js

**Comment by KyleABrown** [comment]
Thats what I ended up doing, thank ya!
