### ISSUE TITLE
how to draw shapes in v4 ?

### ISSUE THREAD

**Issue by darkworks** [viliusle/miniPaint#87]
i have this function to draw cross
```
	//draws cross
	this.cross_X = function (ctx, x, y,size=20,col='#ff0000',plus_width) {
	x = parseFloat(x);
	y = parseFloat(y);
	size = parseInt(size);
	var lw= parseInt(plus_width);
		
		ctx.beginPath();
		ctx.moveTo(x - size, y - size);
		ctx.lineTo(x + size, y + size);
		ctx.lineWidth = lw;
		ctx.strokeStyle = col;
		ctx.stroke();

		ctx.moveTo(x + size, y - size);
		ctx.lineTo(x - size, y + size);
		ctx.lineWidth = lw;
		ctx.strokeStyle = col;
		ctx.stroke();
	};
```
so first i select or create cross_layer  by calling my cross_layer_manager() function
```
	cross_layer_manager() {		
		for(let layer of config.layers){
			if( layer.gtype.toLowerCase().includes('cross') || layer.name.toLowerCase().includes('cross')){
				this.Base_layers.select(layer.id);	
				return true;
			}
		}
		// create cross layer
			var new_layer = {
				name: 'cross_layer',
				type: 'image',
				gtype: 'cross_layer',
				width: config.WIDTH,
				height: config.HEIGHT,
				width_original: config.WIDTH,
				height_original: config.HEIGHT,			
			};
			this.Base_layers.insert(new_layer);
		return true;
	}
```
then i do 
```

			var canvas = this.Base_layers.convert_layer_to_canvas(null, true);
			var ctx = canvas.getContext("2d");	
                       cross_X(ctx,xc,yc,size,col,pwidth);
```

but its not drawing on selected cross_layer created by cross_layer_manager 

any idea what am doing wrong

thanks

**Comment by viliusle** [comment]
Related wiki: https://github.com/viliusle/miniPaint/wiki/Extending

If you want to add something, you have 2 ways: 

- add layer with image (image will be draw on every render). Example: https://github.com/viliusle/miniPaint/blob/master/src/js/modules/file/open.js#L121
- add layer with type "SomeType" (define parameters, like x, y, width, height, color). If type is known to system (look in /src/js/tools/*) it will be automaticalle rendered. If type in unknown, like SomeType, you also have to register render function (create file in /src/js/tools/SomeType.js with function render() ) to tell system what to do without your new layer.

Smallest example about rule 2:

1. Register new layer with type "borders": https://github.com/viliusle/miniPaint/blob/master/src/js/modules/tools/borders.js#L62
2. Define render function: https://github.com/viliusle/miniPaint/blob/master/src/js/tools/borders.js#L19

Also remember, there is no canvas in system to intereact, there are layers, these layers are draw on main canvas, but canvas are cleared often, and layers are re-draw on that canvas many times. 

Let me know if something is not clear, i will add more info in wiki then.

**Comment by darkworks** [comment]
hmmm ya i know modules are top menu functionality and tools are right side gui menu functionality , i have added one module which i needed  which is working , however i not need user interaction so my goals was to automatically draw cross it its layer by calling cross_X function and before that i create layer for it using cross layer manager function , which i attached above , 
any way i will play a bit more with it , let see how it goes

**Comment by darkworks** [comment]
i was able to draw directly on other image layers 
so one Question how can i create blank image layer so that i can draw on it , like currently when i select existing image layer with any image and i do 
			var canvas = this.Base_layers.convert_layer_to_canvas(null, true);
			var ctx = canvas.getContext("2d");	
                       cross_X( ......... ) // cross function 
                       this.Base_layers.update_layer_image(canvas); 	//save	

then crosses are rendered on that image layer 
so how can i create blank image layer  so that on top of them i can draw like i did by selecting another image layer and worked

**Comment by darkworks** [comment]
ok got it 

data: canvas.toDataURL("image/png"),

**Comment by darkworks** [comment]
made me tired :( 
 when i do this from GUI , Layer > New    it create new layer and then i convert it to raster Layer > convert to raster  and then i do 
```
			var canvas = this.Base_layers.convert_layer_to_canvas(null, true);
			var ctx = canvas.getContext("2d");	
                       cross_X( ......... ) // cross function 
                       this.Base_layers.update_layer_image(canvas); 	//save	
```
i get drawing on new created layer from cross_X function 

but when i do grammatically 
```
	cross_layer_manager() {		
		window.State.save();
		this.Base_layers.insert();
		this.raster.raster();
		return true;
     }
cross_layer_manager() ;
			var canvas = this.Base_layers.convert_layer_to_canvas(null, true);
			var ctx = canvas.getContext("2d");	
                       cross_X( ......... ) // cross function 
                       this.Base_layers.update_layer_image(canvas); 	//save	

```


then it not work get error :( 

> Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
>     at base-layers.js:851

**Comment by viliusle** [comment]
which browser and version you are using? System tries to add image using blob (faster) and it fails, strange.

You can update image layer in other, but slower way:
```
var layer_link =  this.Base_layers.get_layer(layer_id); //your layer_id
layer_link.link.src = canvas.toDataURL(); //your canvas
this.Base_layers.render();
```

**Comment by viliusle** [comment]
To add image from canvas:

```
var canvas = document.createElement('canvas');
canvas.width = config.WIDTH;
canvas.height = config.HEIGHT;

//add something to canvas

//register it
var params = [];
params.type = 'image';
params.name = 'Fill';
params.data = canvas.toDataURL("image/png");
params.width = canvas.width;
params.height = canvas.height;
this.Base_layers.insert(params);
```

**Comment by darkworks** [comment]
am using chrome

**Comment by darkworks** [comment]
tried this 
```
var canvas = document.createElement('canvas');
canvas.width = config.WIDTH;
canvas.height = config.HEIGHT;

//add something to canvas

//register it
var params = [];
params.type = 'image';
params.name = 'Fill';
params.data = canvas.toDataURL("image/png");
params.width = canvas.width;
params.height = canvas.height;
this.Base_layers.insert(params);
```

same error :( 
i wonder if we can create  empty image type layer by fly or not ,  in earlier version by default layer type was IMAGE , and i think in v4 its vectors , so this conversion is problem , i think i should have to introduce few miliseconds delay in it ? but looks to me not good solution

**Comment by darkworks** [comment]
tried this 
```
var layer_link =  this.Base_layers.get_layer(layer_id); //your layer_id
layer_link.link.src = canvas.toDataURL(); //your canvas
this.Base_layers.render();
```
but getting error

`gview-tools.js:385 Uncaught TypeError: Cannot set property 'src' of null`

**Comment by viliusle** [comment]
Give me few days, i will finish debug this. Almost sure that issue is related with adding data and instantly trying to edit that before it is added. Fix will be something like timeout (=evil), but better:, callbacks or async + await.

**Comment by darkworks** [comment]
thanks :) 

ya currently am handling this issue with async  and await  promises
