### ISSUE TITLE
Save Project

### ISSUE THREAD

**Issue by gabriellima** [viliusle/miniPaint#88]
Would it be possible to save the whole project, so as to continue working on it later?

**Comment by gabriellima** [comment]
I just noticed the Quick Save and Quick load option, to store it in browser storage. 

Although I was thinking about many project files, this already solve my needs. Thank you.

**Comment by viliusle** [comment]
If you can not afford to loose data or data is big, use save as JSON. (This is similar to PSD)
"Quick Save" and "Quick load" data can be lost after clearing browser history fro example.
