### ISSUE TITLE
image Data not updating after shift

### ISSUE THREAD

**Issue by darkworks** [viliusle/miniPaint#89]
![iymv2p6aqcioxupjnbj2ug 1](https://user-images.githubusercontent.com/12841788/36959069-f6ac1b8a-2061-11e8-966a-f731ae053ccf.png)

i have noticed that image data is not updated when layer is shifted , you can see screenshot i attacked 
you will see red cross its old location , when i try to search for square i land on their old location even visually they are shifted ,

**Comment by viliusle** [comment]
maybe you try to access data too early? Updating image Data takes some time ... Simple test would be access data after 1s with timeout. (dont use it on live code of course).

**Comment by darkworks** [comment]
no i give it a lot of time ,

**Comment by viliusle** [comment]
Please describe **exactly** what are you doing.

Are you trying to change layer starting position (0x0 -> x,y) and get image data? If yes, on layer position change, image data is not changed.

**Comment by darkworks** [comment]
ya right , i was changing its position , got it 

thanks
