### ISSUE TITLE
Image trim not work..etc.

### ISSUE THREAD

**Issue by maxmas** [viliusle/miniPaint#9]
This editor is a great work, I very love it.
And I have some questions. 
My browser is Chrome.
I upload three images into the editor.
I choose one image, and click select area tool to mark a area, 
then choose Image -> Trim, but nothing happened, it not work, I do not know how it work.
But if I click select area tool to mark a area, 
then choose Image -> Crop Selection, all images (layers) will be crop together as same size, it should not do this.

And I also do not know the Layer->Trim, how it work.
Thanks!

By the way, Your project is same this one https://github.com/Jayuda/ImageUp.
So, who is author? who is plagiarize?

**Comment by viliusle** [comment]
will be fixed on 1.9.6 version.
