### ISSUE TITLE
Text wrap by default

### ISSUE THREAD

**Issue by avalero85** [viliusle/miniPaint#91]
First of all congratulations for the plugin. It looks very good ;)

I only have one question...Is it possible to use line breaks with the text tool?

Thanks in advance

**Comment by viliusle** [comment]
Not possible now, but I am planning to add it.

**Comment by avalero85** [comment]
Thank you very much for your answer.

The truth is that this plugin is great for an application that I am developing and the only problem is that. I will try to develop this functionality on my own. Any advice before I start? Unless you tell me that you have planned to do in the next...¿month?. In that case I'll wait for him hehehe :P

Thanks in advance

**Comment by viliusle** [comment]
https://github.com/viliusle/miniPaint/blob/master/src/js/tools/text.js#L157
This should be replaced with some library that supports text wrap. Also live edit on screen (not in text box that we have now) should be nice to have.
It is possible to have it this month on master, but research must be done about above. No promises yet.

**Comment by avalero85** [comment]
Great! 

I will keep you informed of my progress.

**Comment by avalero85** [comment]
My provisional solution:
```javascript
if (stroke == false) {
	var lineBreaks = (text.match(/\n/g)||[]).length;
	var lines = text.split('\n');
	for(var i = 0; i <= lineBreaks; i++) {	
		ctx.fillText(lines[i], start_x, layer.y + (size * i));
	}
} else {
	ctx.strokeText(text, start_x, layer.y);
}
```

**Comment by avalero85** [comment]
I improve my first solutions:

```javascript
var lineBreaks = (text.match(/\n/g)||[]).length;
var lines = text.split('\n');
var j = 0;
var caractersPerLine = parseInt(layer.width * parseInt(size * 1.5) / 100);
for(var i = 0; i <= lineBreaks; i++) {					
	if(caractersPerLine < lines[i].length) {
		var customLines = lines[i].match(new RegExp('.{1,' + caractersPerLine + '}', 'g'));
		if(customLines) {
			customLines.forEach(line => {
				j++;
				ctx.fillText(line, start_x, layer.y + (size * (i + j)));
			});
		} else {
			ctx.fillText(lines[i], start_x, layer.y + (size * (i + j)));
		}
	} else {
		ctx.fillText(lines[i], start_x, layer.y + (size * (i + j)));
	}
}
```

Now the text is adjusted to its container.
