### ISSUE TITLE
ReBuilding with latest webpack

### ISSUE THREAD

**Issue by jprules321** [viliusle/miniPaint#93]
Hello, this may sound dumb but I'm new to NPM and I can't figure out how to rebuild your SRC.

I installed NPC and Webpack, but I always get errors because I don't know where to put the Src files to make the bundle, also git commands in the cmd don't work. Any help would be greatly appreciated

**Comment by viliusle** [comment]
Git should be installed globally.
Also wiki should help: https://github.com/viliusle/miniPaint/wiki/Build-instructions

>where to put the Src files
you don't need to move any files, just git clone or download code, then do "npm update" to install libs and "webpack" to build once.

But we can help you more if you tell exactly what errors you get.

**Comment by jprules321** [comment]
Succesfuly cloned using GIt, it installed in System 32, I did CD Minipaint and NPM Update which download node_modules. When I type webpack it seems to be trying to run it from another directory would that be my problem ?

![webpack](https://user-images.githubusercontent.com/37819280/37994904-e98f108e-31e0-11e8-860d-d2a16fc0a4f3.png)

**Comment by jprules321** [comment]
Alright, last error was cannot find module. I uninstalled node and everything and re-did the whole process. Now I get this
![mewerr](https://user-images.githubusercontent.com/37819280/38060468-e69b3758-32b8-11e8-9327-00c99370e536.png)

**Comment by viliusle** [comment]
Your latest issue is related with webpack 4 trying to build project that is tested only with webpack 3. Sorry for that :). Your global webpack is v4, while project uses v3.

Short term fix would be runing local webpack, not global, by doing one of these commands:
`npx webpack`
`node_modules/.bin/webpack`

Issue replicated on unix, and commands above fixed it. ON win should be same, will test later.
But i should update project to make it work with latest webpack, will work on that in next days.

p.s. dont close ticket.

**Comment by jprules321** [comment]
Thanks so much. 

Great work on this by the way, really awesome and well done.

PS. hermite_resize don't seem to download properly with NPM Update, had to manually get it and put it in node_modules.

**Comment by soWizardly** [comment]
when you install the webpack version listed in packages.json for the first time on your machine, it suggests you install webpack-cli to build changes. It tries to install a version of webpack-cli which requires webpack v4. Just run `npm install -g webpack-cli@1.4.6`, which should download the right version globally so `webpack-cli` command works.

This worked for me:

**Comment by viliusle** [comment]
Support for latest webpack (4) added. 
Commit: https://github.com/viliusle/miniPaint/commit/8fbe31d0fef6fb8b6c428d2883528f543a836e62
