### ISSUE TITLE
Rotated Image

### ISSUE THREAD

**Issue by drekoes** [viliusle/miniPaint#94]
Can I save the rotated image, without the white background?

**Comment by viliusle** [comment]
First, use magic wand, or replace color tool to remove background and replace it to transparent.. Rotation does not add background. And save using PNG of course.

If you still have problems, give more info.

**Comment by drekoes** [comment]
fyi here are the steps i did : Open File, Set Image > Rotate, Save. I've tried to remove the white space using crop (just like I used to do in Photoshop), but still it didn't work. It succes cropped the background, but the rotated image became smaller :(

**Comment by viliusle** [comment]
Sorry for delay, only now i understand you and know where problem is. Please do this:
Tools > settings > Transparent > Turn it on > Save.
You only need to do it once. After that system will allow transparency.
