### ISSUE TITLE
Open a specific file on startup.

### ISSUE THREAD

**Issue by STPJ** [viliusle/miniPaint#97]
Hi, trying to find that in the doc. 

Checking the code now, can you point me where I can find to open the viewer on a specific file on startup? Without Human interactions?

The Filename will be dynamic loaded by a Ajax query.
(Choosing a new image file in a select box, will trigger a new Image editor with picture opened as default)

**Comment by viliusle** [comment]
check examples folder:

https://github.com/viliusle/miniPaint/blob/master/examples/open-edit-save.html#L84
