### ISSUE TITLE
Support mobile touch events

### ISSUE THREAD

**Issue by Bartheyrman22** [viliusle/miniPaint#98]

**Comment by Bartheyrman22** [comment]
Would this be useful/wanted?

**Comment by Bartheyrman22** [comment]
Pull request related to this issue:
#101

**Comment by viliusle** [comment]
Yes, very useful. I will check pull request.

**Comment by Bartheyrman22** [comment]
Thanks,

Some tools need multitouch to work decently, for instance the 'clone' tool.

Maybe an implementation of hammer.js is an option?

There is also an issue with the erase tool on a mobile touch device. But don't understand easy how this tool is different compared to the others. It seems to me that the events for this tool are executed in a different order.

**Comment by viliusle** [comment]
Status update: pull request merged, but i still need to check erase.

**Comment by viliusle** [comment]
It was done after big break, but finally other tools got touch support: e3d3d0d3a4796cdc1597db3f4bb21e8450ce814b

We still need to test it using real touch device, not only emulator like i did.
